ROFO-30 RestClient 설정
Weit-2nd/roady-foody-server pull request #10
Opened 2024-06-12 06:10 UTC by jifrozen0110

### 개요

### 변경사항
* UserNotFoundException과 같은 도메인 전용 Exception은 해당 도메인 User 패키지 아래에서 관리
* RestClient의 timeout 설정
* RetryIntercaptor 외부 API에게 Too Many Requests 상태 코드를 반환받을 시 API 요청 재시도 로직
* RetriesExceededException 재시도 실패 에러 생성

### 테스트
- 테스트 코드 추가여부 O/X x
- 테스트 코드가 추가되지 않았다면 그 이유를 적어주세요.
RestClient관련 test 문서 찾아보고 추가할 수 있으면 추가하겠습니다!

### 관련 지라 및 위키 링크
 - [JIRA](https://weit-2nd.atlassian.net/browse/ROFO-30) 

### 리뷰어에게 하고 싶은 말
1. log를 그냥 log.info log.error이렇게 찍으면 될까요?? log/trace 부분을 아직 파악하지 못해 로그를 어떻게 찍으면 좋을지 궁금합니다.
2. restClient를 추가하시려면
RestClient에서 baseUrl이랑 interface 빈 설정하시면 됩니다.

2024-06-12 07:38 UTC, Unagi-zoso commented on src/main/kotlin/kr/weit/roadyfoody/global/client/RestClientConfig.kt
> +    // Todo RestClient에 가상 쓰레드 지정
가상 쓰레드로 바로 적용하지 않은 이유가 있으신가요?

2024-06-12 07:42 UTC, Unagi-zoso commented on src/main/kotlin/kr/weit/roadyfoody/global/client/RestClientConfig.kt
> +        return creatClient("https://jsonplaceholder.typicode.com", TestClientInterface::class.java)
테스트용 API 요청 서비스의 도메인인가 보네요. 처음보는데 유용할 것 같아요

2024-06-12 07:45 UTC, Unagi-zoso commented on src/main/kotlin/kr/weit/roadyfoody/test/presentation/api/TestController.kt
> +    fun rest(): TodoResponse {
이 Test API 의 테스트 코드를 작성하지 않은 이유가 있으신가요?

2024-06-12 07:50 UTC, Unagi-zoso commented on src/test/kotlin/kr/weit/roadyfoody/test/controller/TestControllerTest.kt
> +    @MockBean private val testClientInterface: TestClientInterface,
이 Mock 객체가 없을 때 어떤 일이 일어나는지 알 수 있을까요?

2024-06-12 07:51 UTC, Unagi-zoso reviewed
중요한 작업을 빠르게 잘 처리해주셔서 너무 감사하네요!
제가 잘 모르는 부분이 있어 질문 댓글 좀 남겼습니다.

2024-06-12 10:03 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/global/client/RestClientConfig.kt
> +    // Todo RestClient에 가상 쓰레드 지정
굳이 큰 이유는 없고 리뷰해서 확인받고 지정하려고 했습니다!

2024-06-12 10:04 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/test/presentation/api/TestController.kt
> +    fun rest(): TodoResponse {
test 패키지 자체가 곧 지워질 코드라고 생각하였습니다.
따라서, RestClient를 실제로 사용할때 test 코드를 작성하고자 하여 작성하지 않았습니다.

2024-06-12 10:13 UTC, jifrozen0110 commented on src/test/kotlin/kr/weit/roadyfoody/test/controller/TestControllerTest.kt
> +    @MockBean private val testClientInterface: TestClientInterface,
TestController는 TestClientInterface를 의존성 주입받고 있습니다.

하지만 테스트 코드 어노테이션중에 @WebMvcTest(TestController)는 TestController와 Controller를 위한 구성요소들만 빈으로 등록됩니다. (아마 단위테스트를 위해 그런걸로 알고있습니다!)
따라서 TestClientInterface가 테스트 환경에서는 빈으로 등록되지 않아 @MockBean을 사용하여 가짜 빈을 만들고 주입 받아야합니다.

2024-06-12 10:14 UTC, Unagi-zoso approved these changes

2024-06-12 11:45 UTC, konempty requested changes
크 고생많으셨어요!
저도 RestClient는 처음써봐서 궁금한데 쓰기 간편해보이네요 ㅋㅋㅋㅋ
리뷰 쪼금 남겼으니까 적용하실만한건 적용 부탁드립니다~!

2024-06-12 11:45 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/common/exception/ErrorCode.kt
> +    RETRIES_EXCEEDED_ERROR(HttpStatus.SERVICE_UNAVAILABLE, -11000, "외부 API 호출 재시도 횟수 초과"),
앗 ㅋㅋㅋ.. 503을 사용하셨는데
요건 아예 서버가 뻗어버려서 요청 처리가 불가능한 상황을 주로 나타내고
K8S환경에서는 인그레스에 문제가 있을때 발생하는 에러라 좀더 보편적인 500으로 처리해주시면 좋을것 같습니다!

2024-06-12 11:45 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/global/client/RetryClientHttpRequestInterceptor.kt
> +    private val attempts = 3
요것 Static 상수로 선언하는게 어떨까요??

2024-06-12 11:45 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/user/exception/UserNotFoundException.kt
> +class UserNotFoundException(message: String) : BaseException(ErrorCode.NO_SUCH_ELEMENT, message)
NO_SUCH_ELEMENT를 써도 한동안은 문제 없을것 같은데
NO_SUCH_ELEMENT가 너무 범용적인 에러코드라 나중에는 이곳 저곳에서 다 쓸것 같네요 ㅋㅋㅋ...
유저가 없다는 에러코드를 하나 새로 추가하는게 어땠을까요??
요건 단순 추천이라 적용하지 않아도 괜찮습니다~!

2024-06-12 11:45 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/global/client/RestClientConfig.kt
> +                .withReadTimeout(Duration.ofSeconds(5L))
ㅋㅋㅋ 요렇게 숫자를 그냥 넣어놔도 나쁘진 않은데
상수로 처리하면 더 좋을것 같아요!

2024-06-12 11:45 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/global/client/RetryClientHttpRequestInterceptor.kt
> +import java.net.http.HttpRequest
요 import는 사용이 안되는데 임포트 하신이유가 있을까요??

2024-06-12 11:45 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/global/client/RetryClientHttpRequestInterceptor.kt
> +        request: org.springframework.http.HttpRequest,
위 import때문에 여기가 어색해졋네요 ㅋㅋㅋㅋㅋ

2024-06-12 11:45 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/global/client/RetryClientHttpRequestInterceptor.kt
> +                // Todo 로그 추가 필요할까요?
요건 있으면 좋고 없어도 좋고 지언님 편하신대로 하시면 됩니다~!
대신 Json 포멧으로 남겨야지만 나중에 ElasticSearch에서 검색이됩니다 ㅋㅋㅋ

2024-06-12 11:46 UTC, konempty commented
아 그리고 필수는 아니고 선택이라 넘어가신것 같은데 PR올리시기전에 K8S환경에 문제 없는지 샌박에서 확인 한번씩 해주시면 좋을것 같아요~!

2024-06-12 11:49 UTC, konempty commented
ㅋㅋㅋ 그리고 질문을 지금봤네요

> log를 그냥 log.info log.error이렇게 찍으면 될까요?? log/trace 부분을 아직 파악하지 못해 로그를 어떻게 찍으면 좋을지 궁금합니다.

네넵 그냥 찍으시면 되는데 제가 리뷰에 남긴것처럼 Json형식으로 남기면 파싱이 가능해서 ES에서 조회가 가능하구요
단순히 디버깅 혹은 기록 남기기용이라면 plainText로 남겨도 됩니다!

> 찾아보니 restClient 부분에 [가상쓰레드](https://0soo.tistory.com/261#RestClient%EC%--%--%--%EA%B-%--%EC%--%--%--%EC%-A%A-%EB%A-%--%EB%--%-C%--%ED%-C%A-%ED%--%A-%EB%A-%AC%--%EC%A-%--%EC%A-%--%ED%--%--%EA%B-%B-) 지정을 하던데 해당 부분 도입해도 괜찮을까요?

으흠 네넵 도입하셔도 되는데 가상쓰레드를 쓴다는건 API요청을 비동기화 하신다는 의도일까요??
비동기로 API를 호출하는게 아닌 동기로 호출하는거면 오히려 성능이 떨어질거예요

2024-06-12 11:54 UTC, Unagi-zoso commented on src/main/kotlin/kr/weit/roadyfoody/user/exception/UserNotFoundException.kt
> +class UserNotFoundException(message: String) : BaseException(ErrorCode.NO_SUCH_ELEMENT, message)
이건 제가 이후 유저 관련 기능 만들면서 반영해볼게요!

2024-06-12 11:56 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/user/exception/UserNotFoundException.kt
> +class UserNotFoundException(message: String) : BaseException(ErrorCode.NO_SUCH_ELEMENT, message)
아하 네넵 그러면 요 리뷰는 지언님이 적용 안하셔도 될것같습니다~!

2024-06-12 15:50 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/global/client/RetryClientHttpRequestInterceptor.kt
> +import java.net.http.HttpRequest
앗 자동 import 를 사용하는데 있어 잘못 들어간것같습니다! 바로 수정하였습니다.

2024-06-12 15:50 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/global/client/RetryClientHttpRequestInterceptor.kt
> +                // Todo 로그 추가 필요할까요?
감사합니다 우선 주석으로 남겨두겠습니다!

2024-06-12 16:01 UTC, jifrozen0110 commented
넵 비동기화하려고 하였는데 작업의 우선순위가 낮은 것 같아 리팩토링요소로 메모해두겠습니다!
리뷰 감사합니다!

2024-06-13 01:54 UTC, konempty approved these changes
고생하셨습니다 👍 👍

2024-06-13 06:29 UTC, merged