ROFO-37 관광공사 검색 API 연동
Weit-2nd/roady-foody-server pull request #14
Opened 2024-06-17 16:14 UTC by jifrozen0110

### 개요

### 변경사항
* 관광공사 API를 위한 Key를 관리하기 위해 properties 생성
* RestCilentConfig Exception 추가
* RestClient 가상 스레드 설정
* 관광공사 검색 API 연동
* 빈문자열 처리를 위한 ItemsDeserializer 생성
* 키워드 검색 API

### 테스트
- 테스트 코드 추가여부 O/X O
- 테스트 코드가 추가되지 않았다면 그 이유를 적어주세요.

### 관련 지라 및 위키 링크
 - [JIRA](https://weit-2nd.atlassian.net/browse/ROFO-37) 

### 리뷰어에게 하고 싶은 말
1. 기획과 변경된 내용
기존 - 관광지 키워드 검색 API와 행사 정보 조회 API를 사용하기로 하였는데
행사 조회 API의 경우 키워드 검색이 불가능하여
키워드 검색 API에서 content_id(12 - 축제/행사 , 15 - 관광지)를 달리하는 방식으로 구현

2. restClient 가상 스레드 도입

3. 키워드 검색 API를 contentId를 달리하여 두번 API를 호출하고 이를
하나의 결과값으로 반환해야합니다.
따라서 다음과 같은 3가지 방식을 고민하였는데요

> 1. 페이지 row를 반으로 나눠서 각각 요청하기
> 예시:
> 클라이언트로부터 페이지 row가 10으로 요청받음
> 행사 키워드 검색 외부 API -> 5 row 요청
> 관광지 키워드 검색 외부 API -> 5 row 요청
> 두 결과를 합쳐서 반환
> 
> 2. 각 API에 전체 row 요청하기
> 예시:
> 클라이언트로부터 페이지 row가 10으로 요청받음
> 행사 키워드 검색 외부 API -> 10 row 요청
> 관광지 키워드 검색 외부 API -> 10 row 요청
> 두 결과를 합친 후, 페이지네이션 처리를 통해 클라이언트에 반환
> 
> 3. 결과 다 받아와서 페이지네이션 처리하기
> 클라이언트로부터 페이지 row가 10으로 요청받음
> 행사 키워드 검색 외부 API -> 필요한 모든 데이터를 요청
> 관광지 키워드 검색 외부 API -> 필요한 모든 데이터를 요청
> 두 결과를 병합하여 클라이언트가 요청한 페이지 row 만큼만 반환

팀장님과 상의하여 2번을 채택하였습니다.

하지만 또 문제점이 있었는데
**각 데이터를 가져와서 10개를 어떤 기준으로 반환해줘야할까?** 라는 고민을 하기 시작하였습니다.

이에 대해 처음에는 랜덤하게 데이터를 반환해주었는데요 -> 이유는 페이지네이션이 아니니 못받는 데이터는 계속해서 못받을것같아 이렇게 생각하였습니다.

근데 다시 생각해보니 캐싱을 해야할 수도 있으니 계속해서 값이 랜덤하게 바뀌면 안되겠더라구요.

그래서 수정일순으로 정렬한 후(최신 데이터를 가져오기 위해) Tour와 Festival을 하나씩 가져오도록 개발하였습니다.

2024-06-18 03:01 UTC, Unagi-zoso commented on src/main/kotlin/kr/weit/roadyfoody/global/client/RestClientConfig.kt
> +    private val virtualThreadEnabled: Boolean = false
spring 가상쓰레드 활성 플래그를 여기서도 활용할 수 있군요!
좋은거 같아요!

2024-06-18 04:00 UTC, konempty requested changes
진짜 고생 많으셨습니다 👍 👍 
지언님 코드에서도 많은걸 고민한게 느껴져서 너무 좋습니다~!
코멘트 쪼금 남겼으니까 확인하시고 반영할만한건 반영 부탁드립니다!

2024-06-18 04:00 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/common/exception/ErrorCode.kt
> +    REST_CLIENT_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, -11000, "외부 API 호출 중 에러 발생"),
RETRIES_EXCEEDED_ERROR와 REST_CLIENT_ERROR의 에러코드가 -11000로 동일한데 의도된걸까요??

2024-06-18 04:00 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/tourism/application/service/TourismService.kt
> +        log.info("Time : {} ms", end - start)
요건 디버깅용 로그인것 같은데 로컬에서만 임시로 확인하고 프로덕션 코드에는 반영이 안되면 좋을것 같아요!

2024-06-18 04:00 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/tourism/application/service/TourismService.kt
> +                it.mapX != null && it.mapX != null
으흠... 요 코드의 의미가 뭘까요..?

2024-06-18 04:00 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/tourism/dto/TourismResponseWrapper.kt
> +    @JsonProperty("title") val title: String,
으흠 json으로 바꿨을때의 이름이 변하지 않는것 같은데 전부 명시하신 이유가 있을까요??

2024-06-18 04:00 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/tourism/dto/SearchResponse.kt
> +    val addr2: String?,
요렇게 하면 클라이언트 개발자가 볼때 고통스러울것 같은데
관광 API로 받은 이름을 그대로 쓰는게 아니라 좀더 직관적인 이름으로 바꿔서 내려주면 좋을것 같아요!

2024-06-18 04:00 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/tourism/application/service/TourismService.kt
> +        }
요 코드를 보면 의도는
리스트에 관광지, 축제, 관광지, 축제 요렇게 번갈아가면서 나오도록 의도하신것 같은데
요 리스트안에서 순서는 상관없을것 같아서 번걸아 나오는 로직은 불필요할것 같아요
그렇다면 좀더 로직을 단순화 할수 있지않을까요??
혹시 리스트에서 번갈아 나오도록 의도하신 이유가 있을까요?

2024-06-18 04:00 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/tourism/config/TourismProperties.kt
> +    val mobileOs: String,
요건 서버 프로퍼티로 고정할게 아니라 클라이언트로 부터 받도록 했어야 하지 않을까요..??
클라이언트로부터 받되, 클라이언트가 보내지 않으면 기본값은 안드로이드로 고정해두면 좋을것 같아요!

2024-06-18 04:00 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/tourism/dto/ItemsDeserializer.kt
> +class ItemsDeserializer : JsonDeserializer<Items>() {
코드의 작동이 이해가 안되는데
요 클래스의 의의는 뭘까요...?

2024-06-18 04:00 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/tourism/presentation/client/TourismClientInterface.kt
> +        @PathVariable(name = "MOBILE_APP") mobileApp: String,
오호 뭔가 어색한것 같은데 PathVariable이 아닌데 PathVariable처럼 쓰신 이유가 있을까요??

2024-06-18 04:00 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/user/security/config/SecurityConfig.kt
> +        "/api/v1/tourism/**",
얘는 시큐리티 필터를 우회하면 안될것 같아요! ㅋㅋㅋㅋ

2024-06-18 04:00 UTC, konempty commented on src/test/kotlin/kr/weit/roadyfoody/global/client/RetryClientHttpRequestInterceptorTest.kt
> +            then("세 번째 시도에서 실패하면 RetriesExceededException을 던진���.") {
오잉 ㅋㅋㅋ 문자열이 깨졌네요 ㅋㅋㅋ
<img width="73" alt="스크린샷 2024-06-18 오후 12 49 36" src="https://github.com/Weit-2nd/roady-foody-server/assets/44064530/c8ab9997-5107-4a44-951e-6145a9d6fe7c">

2024-06-18 04:00 UTC, konempty commented on src/test/kotlin/kr/weit/roadyfoody/tourism/application/service/TourismServiceTest.kt
> +                    searchResponses.items.size shouldBe ZERO
`searchResponses.items.shouldBeEmpty()`
요걸 쓰는게 좀더 의도를 잘 나타내는것 같아요!

2024-06-18 04:00 UTC, konempty commented on src/test/kotlin/kr/weit/roadyfoody/tourism/presentation/api/TourismControllerTest.kt
> +                then("200 상태 번호화 SearchResponses 반환한다.") {
"번호화" ㅋㅋㅋ 오타네요

2024-06-18 04:00 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/global/client/RestClientConfig.kt
>          private const val TEST_URL = "https://jsonplaceholder.typicode.com"
관광데이터 API가 추가되면 요 테스트용으로 있던 레거시는 지워도 될것 같아요!

2024-06-18 04:00 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/global/config/ThreadConfig.kt
> +    @ConditionalOnThreading(Threading.PLATFORM)
저희가 플랫폼 쓰레드를 사용해서 작업할 일이 앞으로는 없지 않을까 싶은데
미래 대비용으로 추가하신걸까요??

2024-06-18 04:00 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/tourism/application/service/TourismService.kt
> +    private val executor: ExecutorService = Executors.newVirtualThreadPerTaskExecutor()
여기서 선언하는게 아니라 ThreadConfig에서 선언한 빈을 주입받는게 깔끔하지 않을까요??

2024-06-18 04:00 UTC, konempty commented on src/test/kotlin/kr/weit/roadyfoody/tourism/fixture/TourismFixture.kt
> +    private const val FESTIVAL_RESPONSE_SIZE_0 = "payload/festival-search-response-size-0.json"
오호 파일을 불러와서 테스트에서 사용하는거 괜춘하네요 ㅋㅋㅋㅋ 👍 👍

2024-06-18 04:23 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/tourism/application/service/TourismService.kt
> +                it.mapX != null && it.mapX != null
응답에서 좌표값이 없는 응답은 빼는 코드입니다!
mapX와 mapY가 필수 응답값이 아니여서 좌표값이 있는 응답간만 필터링 하였습니다.

2024-06-18 04:48 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/tourism/dto/TourismResponseWrapper.kt
> +    @JsonProperty("title") val title: String,
테스트 코드 돌릴때 인식이 안되는 문제와 < 주요 범인
modifiedtime -> modifiedTime
일부 필드를 카멜 케이스로 바꿔줘야해서 모두 JsonProperty를 사용하게 되었습니다.

2024-06-18 04:48 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/global/config/ThreadConfig.kt
> +    @ConditionalOnThreading(Threading.PLATFORM)
앗 그렇군요!
제가 잘못생각하던 부분이 있었던것같습니다.
버츄얼 스레드를 위해 기본적으로 플랫폼 스레드도 설정이 필요하다고 생각하였습니다!
아직 스레드에 대한 이해가 크지않아 생긴 문제같습니다. 필요없는 설정은 지우겠습니다. 감사합니다

2024-06-18 05:05 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/common/exception/ErrorCode.kt
> +    REST_CLIENT_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, -11000, "외부 API 호출 중 에러 발생"),
[002da45](https://github.com/Weit-2nd/roady-foody-server/pull/14/commits/002da45d98dc5c57305c66541502c026a5557379)

아닙니다! 수정하였습니다

2024-06-18 05:06 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/tourism/application/service/TourismService.kt
> +        log.info("Time : {} ms", end - start)
[c5542fa](https://github.com/Weit-2nd/roady-foody-server/pull/14/commits/c5542faf2e7ee5d85cb01bafc50ee6c9606eb644)

2024-06-18 05:06 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/tourism/dto/SearchResponse.kt
> +    val addr2: String?,
[e5de115](https://github.com/Weit-2nd/roady-foody-server/pull/14/commits/e5de115576cca03b5abaf0e455a24ae86a50332a)

2024-06-18 05:09 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/tourism/application/service/TourismService.kt
> +        }
클라이언트에서 10개를 요청했을때
서버 상에서는
관광지 키워드 검색 API 10개
축제 키워드 검색 API 10개 총 20개를 반환받는데
여기서 10개를 어떻게 골라서 반환해줘야할지 고민하였습니다.
두가지 방식을 고안하였고
1. 랜덤하게 반환 -> 캐싱 불가
2. 관광지 5개 축제 5개 나오게 반환
2번째 방식으로 채택하여 개발하였습니다.

2024-06-18 05:10 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/tourism/config/TourismProperties.kt
> +    val mobileOs: String,
클라이언트가 AND로 고정값이라고 생각하였는데
혹시 IOS 확장성으로 인해 클라에서 받아야하는것인가요?

2024-06-18 05:12 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/tourism/dto/ItemsDeserializer.kt
> +class ItemsDeserializer : JsonDeserializer<Items>() {
관광공사에서 item이 없는 응답값을 받게되면
items에 빈배열이 오는게 아니라 "" 빈문자열이 넘어옵니다.

```
{
  "response":{
    "header":{
      "resultCode":"0000",
      "resultMsg":"OK"
    },
    "body":{
      "items":"",
      "numOfRows":0,
      "pageNo":1,
      "totalCount":0
    }
  }
}
```

그래서 해당 빈 문자열의 처리가 필요하여 ItemsDeserializer를 진행해줬습니다.

2024-06-18 05:25 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/tourism/presentation/client/TourismClientInterface.kt
> +        @PathVariable(name = "MOBILE_APP") mobileApp: String,
listYN=Y / arrange=C 이런 디폴트로 설정해줘야하는 파마미터들이 있어서 이거랑 RequestParam을 사용하면 동작을 안하더라구요.
그래서 풀 path를 써주고 필요한 변수를 PathVariable로 넣어주도록 하였습니다.

2024-06-18 05:28 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/tourism/application/service/TourismService.kt
> +    private val executor: ExecutorService = Executors.newVirtualThreadPerTaskExecutor()
[ecf3e3f](https://github.com/Weit-2nd/roady-foody-server/pull/14/commits/ecf3e3fc53ea5b180635bc6b1458e44da91b8168)

2024-06-18 05:28 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/global/client/RestClientConfig.kt
>          private const val TEST_URL = "https://jsonplaceholder.typicode.com"
[77ab3aa](https://github.com/Weit-2nd/roady-foody-server/pull/14/commits/77ab3aab15d162118c5b1d1558b918f3b8f33c47)

2024-06-18 05:29 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/user/security/config/SecurityConfig.kt
> +        "/api/v1/tourism/**",
앗 개발용으로 뚫었는데 까먹었네요 수정하겠습니다!
[c6b4555](https://github.com/Weit-2nd/roady-foody-server/pull/14/commits/c6b455586bc1c4a13105d6ee95203e98461bdedb)

2024-06-18 05:33 UTC, jifrozen0110 commented on src/test/kotlin/kr/weit/roadyfoody/tourism/application/service/TourismServiceTest.kt
> +                    searchResponses.items.size shouldBe ZERO
[0e60a3a](https://github.com/Weit-2nd/roady-foody-server/pull/14/commits/0e60a3a366f3937121c093771201b8967d5a2535)

2024-06-18 13:45 UTC, Unagi-zoso commented on src/main/kotlin/kr/weit/roadyfoody/global/swagger/v1/SwaggerTag.kt
> +    const val TOURISM: String = "C. 관광지 검색 API"
전 기능 만들때 Swagger Tag 앞에 붙는 영어를 
어떤 기준으로 정해야할 지 좀 고민이 되더라구요. .
혹시 비슷한 고민을 하시진 않으셨나요..

2024-06-18 13:55 UTC, konempty requested changes
너무 고생 많으신데
쪼금만더 수정부탁드립니다..!

2024-06-18 13:55 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/global/swagger/v1/SwaggerTag.kt
> +
요거 알파벳 순서에 맞게 정렬하면 예쁠것 같아요 ㅋㅋㅋㅋ
그리고 궁금한게 있는데 A다음에 B가 아니라 C로 선택하신 이유가 있을까요??

2024-06-18 13:55 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/tourism/application/service/TourismService.kt
> +    private val log: Logger = LoggerFactory.getLogger(TourismService::class.java)
요거 사용처가 없는것 같은데 지우는게 어떨까요??

2024-06-18 13:55 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/tourism/application/service/TourismService.kt
> +                it.mapX != null && it.mapX != null
아하 네넵 저도 그런줄 알았는데
mapX만 두번 비교하는건 오타일까요..?? ㅋㅋㅋ

2024-06-18 13:55 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/tourism/application/service/TourismService.kt
> +        }
네넵 저도 2번이 좋다고 생각하는데
제 의도는 아래와 같습니다!
```kotlin
    val mergedItems = filteredTourItems.take(5).toMutableList()
    mergedItems.addAll(filteredFestivalItems.take(10 - mergedItems.size))
```

filteredTourItems의 원소로 최대 5개까지 채우고
10개중에 나머지 빈자리를 filteredFestivalItems의 원소로 채우면 코드가 딱 두줄로 끝날것 같은데
요 원소들을 섞어주는 이유가 궁금했습니다!

2024-06-18 13:55 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/tourism/config/TourismProperties.kt
> +    val mobileOs: String,
ㅋㅋㅋㅋ 네넵 고정값은 맞는데
우리는 확장적인 구조다 라고 주장하기위해 제안해봤습니다 ㅋㅋㅋ
투머치다 싶으면 넘어가셔도 좋습니다~!

2024-06-18 13:55 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/tourism/dto/ItemsDeserializer.kt
> +class ItemsDeserializer : JsonDeserializer<Items>() {
어후 이런 히스토리가 있었군요 ㅋㅋㅋㅋ

2024-06-18 13:55 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/tourism/dto/ItemsDeserializer.kt
> +    @Throws(IOException::class)
요렇게 발생가능한 에러는 굳이 명시 안해줘도 괜찮을것 같아요!

2024-06-18 13:55 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/tourism/dto/TourismResponseWrapper.kt
> +    @JsonProperty("title") val title: String,
ㅋㅋㅋㅋㅋ 네넵 그렇군요
요것도 니즈를 이해했습니다~!

2024-06-18 13:55 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/tourism/presentation/client/TourismClientInterface.kt
> +        @PathVariable(name = "MOBILE_APP") mobileApp: String,
```kotlin

    @GetExchange("/searchKeyword1")
    fun searchTourismKeyword(
        @RequestParam(name = "serviceKey") serviceKey: String,
        @RequestParam(name = "MobileApp") mobileApp: String,
        @RequestParam(name = "MobileOS") mobileOs: String,
        @RequestParam(name = "numOfRows") numOfRows: Int,
        @RequestParam(name = "keyword") keyword: String,
        @RequestParam(name = "contentTypeId") contentTypeId: Int = 15,
        @RequestParam(name = "_type") type: String = "json",
        @RequestParam(name = "pageNo") pageNo: Int = 1,
        @RequestParam(name = "listYN") listYN: String = "Y",
        @RequestParam(name = "arrange") arrange: String = "C",
    ): ResponseWrapper
```

요렇게 디폴트 매개변수를 주면 해결이 되는것 같아보이는데 혹시 확인가능하실까요??

contentTypeId를 디폴트로 주시는거에서 영감을 받았습니다 ㅋㅋㅋ

2024-06-18 13:55 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/user/security/config/SecurityConfig.kt
> +        "/api/v1/tourism/**",
해결 안되었네요 ㅠㅠ

2024-06-18 13:55 UTC, konempty commented on src/test/kotlin/kr/weit/roadyfoody/tourism/application/service/TourismServiceTest.kt
> +private const val FOUR = 4
ㅋㅋㅋㅋㅋ 상수화를 이정도로 할거라곤 예상치 못했네요

2024-06-18 13:55 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/tourism/application/service/TourismService.kt
> +                        12,
12와 15의 의미도 Enum혹은 상수로 관리해주시면 좋을듯합니다~!
너무 매직넘버네요 ㅋㅋㅋ

2024-06-18 14:53 UTC, lin-chae approved these changes
엄청난 양의 코드네요! API 반환값에 따라, 유연한 처리에 감탄했습니다! 고생하셨습니다 👍

2024-06-18 14:53 UTC, lin-chae commented on src/main/kotlin/kr/weit/roadyfoody/global/client/RestClientConfig.kt
> +        if (virtualThreadEnabled) {
restclient를 쓰신 점 좋았습니다. 버츄얼 쓰레드도 한번 공부해봐야겠네여 ㅎㅎ

2024-06-18 15:17 UTC, Unagi-zoso approved these changes
너무 고생하셨네요. 배울 부분이 많은 코드였어요. 👍

2024-06-18 15:17 UTC, Unagi-zoso commented on src/test/kotlin/kr/weit/roadyfoody/tourism/fixture/TourismFixture.kt
> +object TourismFixture {
전 Test Fixture 를 만들 때 최상위 프로퍼티나 메소드로 많이 뒀는데
싱글톤으로 관리를 하시네요.
혹시 어떤 장점을 기대할 수 있는지 알 수 있을까요?

2024-06-18 15:34 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/tourism/application/service/TourismService.kt
> +        }
그렇게 되면 tour가 먼저 5개쭉나오고 그 다음 festival이 나올텐데
뭔가 공평하지 않을것같아서 번갈아 나오도록 선택하였습니다!

2024-06-18 15:38 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/global/swagger/v1/SwaggerTag.kt
> +
A가 동의약관이고
B는 사용자 회원가입 로그인한테 양보해야한다고 생각하였숩나다...ㅎㅎ
정렬하겠습니다!

2024-06-18 15:50 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/tourism/presentation/client/TourismClientInterface.kt
> +        @PathVariable(name = "MOBILE_APP") mobileApp: String,
와! 이렇게 하니깐 정상작동하네요 수정하였습니다!

2024-06-18 15:51 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/tourism/application/service/TourismService.kt
> +                it.mapX != null && it.mapX != null
아이구 수정하겠습니다

2024-06-18 15:53 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/global/swagger/v1/SwaggerTag.kt
> +    const val TOURISM: String = "C. 관광지 검색 API"
헉 맞습니다. 어떤 기준으로 정할지 고민되더라구요!

뭔가 지금으로써 개발순서가 될것같긴한데

아니면 통일성을 위해 목요일 회의때 이야기 나눠보는것도 좋을 것 같아요.

2024-06-18 16:08 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/user/security/config/SecurityConfig.kt
> +        "/api/v1/tourism/**",
해당 설정을 제외하니 테스트 코드에서 Security를 통과하지 못해 오류가 나오는데
로그인 기능이 나오고 나서 삭제하고 반영해도 괜찮을까요??
테스트 코드상에서 인증을 처리하는 방법이 여러개(가짜 토튼 주기, security-test 의존성의 메서드 활용..)가 있을텐데
어떤 방법을 사용해야할지 모르겠습니다.

2024-06-18 16:14 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/global/client/RestClientConfig.kt
> +        if (virtualThreadEnabled) {
확인 감사합니다. 저도 이번 기회에 가상 스레드 공부해봐야겠어요!ㅎㅎ

2024-06-18 16:37 UTC, jifrozen0110 commented on src/test/kotlin/kr/weit/roadyfoody/tourism/fixture/TourismFixture.kt
> +object TourismFixture {
큰 장점은 없는것 같고 프로퍼티나 복잡한 초기화 메서드가 많아진다면 object 클래스로 관리하는것이 더 편리하다고 느꼈습니다.
아무래도 제가 자바를 계속 써와서 클래스안에 필드와 메서드를 가지는게 보기 편하게 느껴지는점과
메서드에서 반복되는 부분은 따로 메서드로 분리하고 상수만 바꿔서 선언하는식으로 진행하여 코드 가독성을 높였습니다.(이건 굳이 object 클래스의 장점은 아니네요)

2024-06-19 01:48 UTC, konempty approved these changes
너무 고생많으셨습니다 👍 👍 
코멘트들 한번씩만 읽어주시면 좋을것 같습니다~!

2024-06-19 01:48 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/tourism/application/service/TourismService.kt
> +        }
으흠... 그렇군요 ㅋㅋㅋ
어차피 클라이언트에서 화면에 뿌릴때 순서가 보장되지 않는 상태로 출력할거라고 예상돼서 
굳이 섞어줄 필요가 없다고 생각했는데 섞어주는것도 나쁘진 않을것 같네요 ㅋㅋㅋㅋ
요건 넘어가도 좋을것 같습니다~!

2024-06-19 01:48 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/user/security/config/SecurityConfig.kt
> +        "/api/v1/tourism/**",
으흠 네넵 정 어려우시다면 요것도 넘어가도 될것 같아요 ㅋㅋㅋㅋ
어차피 지금 시큐리티 통과로직을 추가해도 나중에 로그인 추가하면 재작업 해야할것 같긴하네요

2024-06-19 01:48 UTC, konempty commented on src/test/kotlin/kr/weit/roadyfoody/tourism/application/service/TourismServiceTest.kt
> +private const val FESTIVAL_CONTENT_ID = 15
요건 TourismService에 있는 값들을 public으로 열고 활용하면 굳이 여기서 다시 재정의 할 필요 없지 않을까요??

2024-06-19 01:54 UTC, jifrozen0110 commented on src/test/kotlin/kr/weit/roadyfoody/tourism/application/service/TourismServiceTest.kt
> +private const val FESTIVAL_CONTENT_ID = 15
넵!

2024-06-19 02:25 UTC, merged

2024-06-19 05:23 UTC, Unagi-zoso commented on src/main/kotlin/kr/weit/roadyfoody/user/security/config/SecurityConfig.kt
> +        "/api/v1/tourism/**",
제 생각엔 이게 저희 SecurityConfig 에 있는 Filter 가 다음 로직을 따르거든요. 그래서 userId 헤더를 추가해줘야해요.

```
class MockPassFilter : OncePerRequestFilter() {
    override fun doFilterInternal(
        request: HttpServletRequest,
        response: HttpServletResponse,
        filterChain: FilterChain,
    ) {
        if (request.headerNames.toList().contains("userid")) {
            val userDetails =
                User(
                    "ForDev",
                    "",
                    listOf(
                        SimpleGrantedAuthority("ROLE_USER"),
                    ),
                )
            SecurityContextHolder.getContext().authentication =
                UsernamePasswordAuthenticationToken(userDetails, null, userDetails.authorities)
        }
        filterChain.doFilter(request, response)
    }
}
```

그래서 제가 src/test/kotlin/kr/weit/roadyfoody/support/utils/MockMvcHelper.kt 이 쪽에 테스트 시 쓸만해 보이는 걸 좀 만들긴 했거든요.

```
fun MockHttpServletRequestBuilder.withAuth(): MockHttpServletRequestBuilder = this.header("userid", 1)

fun getWithAuth(url: String) = get(url).withAuth()

fun headWithAuth(url: String) = head(url).withAuth()

fun postWithAuth(url: String) = post(url).withAuth()
```

src/test/kotlin/kr/weit/roadyfoody/tourism/presentation/api/TourismControllerTest.kt (결과 성공)
```
given("GET $requestPath/search 테스트") {
       `when`("키워드로 관광지 검색 요청을 보내면") {
                every { tourismService.searchTourism(2, "강원") } returns createSearchResponses()
                then("200 상태 번호와 SearchResponses 반환한다.") {
                    mockMvc
                        // 사용처
                        .perform(getWithAuth("$requestPath/search?numOfRows=2&keyword=강원"))
                        .andExpect(status().isOk)
```

다음 번에 비슷한 문제가 발생하면 요거 한 번 써보세요. 
로그인 추가 이후로도 이 형태를 사용할지는 고민 중이네요.