ROFO-42 회원가입 API 작성
Weit-2nd/roady-foody-server pull request #18
Opened 2024-06-23 08:06 UTC by Unagi-zoso

### 개요

### 변경사항
- User Entity 프로퍼티 추가, flyway script 작성
- security 패키지 이동 user -> auth
- ImageService 클래스 작성
- KakaoAPI 호출기능 작성
- SwaggerConfig Authorization 헤더 시큐리티 스키마 추가
- 회원가입 관련 기능 및 테스트 작성
- 회원가입 API 문서 작성
- WebPValidator 작성
- Controller 단 통합테스트 어노테이션 작성

### 테스트
- 테스트 코드 추가여부 O

### 관련 지라 및 위키 링크
 - [JIRA](https://weit-2nd.atlassian.net/browse/ROFO-42) 

### 리뷰어에게 하고 싶은 말
어떤 피드백이라도 감사히 잘 받겠습니다!
Swagger 로 문서를 작성하며 DTO 에 스키마 정보를 남기기 싫어
Spec 에 SchemaProperty 필요한 부분들을 정의했습니다.
그냥 하드코딩 느낌으로 하나하나 다 정의하다보니 이후에 변경할 때 번거로울 수 있을 것 같았지만 
그래도 DTO 를 더럽히지 않는다는 점과 MultipartFile 의 경우 @Schema 를 설정해도 적용이 안되는 문제가 있어 현재 방식을 고수하기로 했습니다.
현재 API 문서에서 테스트를 위해선 실제 Kakao Access Token 이 필요합니다. 
전 이 부분을 위해 개인적으로 Kakao Acces Token 을 발급 받고 테스트를 진행했습니다. 
좀 번거로운 부분이 있었는데 이 부분을 개선할 방법이 있을지 고민하고 있습니다.

2024-06-23 08:40 UTC, lin-chae approved these changes
굳굳! 파일에 대한 처리를 잘해주셨네요! 고생하셨습니담! 👍

2024-06-23 08:40 UTC, lin-chae commented on src/main/kotlin/kr/weit/roadyfoody/auth/exception/UserAlreadyExistsException.kt
> +    ErrorCode.INVALID_REQUEST,
리소스가 이미 존재하는 경우 “ 새로운 리소스 추가” 작업의 실패를 표현을 위해 409 에러도 괜찮지 않을까 싶습니다!

2024-06-23 09:32 UTC, jifrozen0110 approved these changes
고생하셨습니다.
통합테스트와 단위테스트를 나눠 꼼꼼하게 테스트를 작성해주셨네요. 배워갑니다!

2024-06-23 09:32 UTC, jifrozen0110 commented on src/test/kotlin/kr/weit/roadyfoody/auth/presentation/api/AuthIntegrationControllerTest.kt
> +class MockKakaoClient : KakaoClientInterface {
테스트를 위한 mock 구현체 만드는거 좋네요!

2024-06-23 09:32 UTC, jifrozen0110 commented on src/test/kotlin/kr/weit/roadyfoody/auth/application/service/AuthIntegrationServiceTest.kt
> +                every { authQueryService.requestKakaoUserInfo(any<SocialAccessToken>()) } returns createTestKakaoUserResponse()
모든 given마다 존재하는데
beforeEach로 묶는거 어떨까요?

2024-06-23 09:32 UTC, jifrozen0110 commented on src/test/kotlin/kr/weit/roadyfoody/auth/application/service/AuthIntegrationServiceTest.kt
> +        given("프로필 사진이 존재하는 경우") {
개인적인 선호도 문제인것같은데
저는 given은 맥락을 명시하고
when으로 특정한 상황을 명시하는걸 선호해서
저라면 AuthCommandServiceTest처럼
given으로 회원가입하는 경우를 묶고
when으로 프로일이 없는경우 있는 경우...
이렇게 나눴을 것 같습니다.

2024-06-23 09:32 UTC, jifrozen0110 commented on src/test/kotlin/kr/weit/roadyfoody/auth/application/service/AuthQueryServiceTest.kt
> +        val kakaoClientInterface = mockk<KakaoClientInterface>()
MockKakaoClient를 생성하였는데 여기선 mockk을 사용해 mock화한 이유가 있을까요?

2024-06-23 09:32 UTC, jifrozen0110 commented on src/test/kotlin/kr/weit/roadyfoody/auth/application/service/AuthIntegrationServiceTest.kt
> +        afterTest { clearAllMocks() }
clearAllMocks을 따로 명시한 이유가 궁금합니다!
mockk에서 자동으로 mock 객체들을 초기화해주지 않나요?

2024-06-23 09:37 UTC, konempty requested changes
고생하셨습니다 👍 👍 
회원가입 API가 빠르게 나왔군요! ㅋㅋㅋㅋ
코멘트 조금 남겼으니 조금만더 수정 부탁드립니다~!

2024-06-23 09:37 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/auth/application/service/AuthCommandService.kt
> +        }
아래와 같이 공통 부분을 아래와 같이 묶어서 밖으로 빼내면 어떨까요??
```kotlin
        val user = User.of(socialId, signUpRequest.nickname)
        userRepository.save(user)
        userAgreedTermCommandService.storeUserAgreedTerms(user, signUpRequest.agreedTermIds)

        if (signUpRequest.profileImage != null) {
            val imageName = imageService.generateImageName(signUpRequest.profileImage.originalFilename)
            user.profile = Profile(signUpRequest.nickname, imageName)
            imageService.upload(imageName, signUpRequest.profileImage) // 외부 저장소 롤백 어려움을 고려해 가장 아래에 배치
        }
```

2024-06-23 09:37 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/auth/dto/SignUpRequest.kt
> +    val socialLoginType: SocialLoginType = SocialLoginType.KAKAO,
여기에 있는 필드들에 기본값이 있는 이유를 알수있을까요??

2024-06-23 09:37 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/auth/presentation/api/AuthController.kt
> +        @Valid @ModelAttribute signUpRequest: SignUpRequest,
ModelAttribute를 붙히는 이유가 뭘까요..?

2024-06-23 09:37 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/auth/presentation/api/AuthController.kt
> +        } ?: throw IllegalArgumentException("socialAccessToken 가 존재하지 않습니다.")
이 코드도 코틀린의 문법을 충분히 활용한것 같긴한데 좀더 적극적으로 활용하면 같은코드를 좀더 짧게 아래와 같이 가능합니다!
```kotlin
requireNotNull(socialAccessToken) { "socialAccessToken 가 존재하지 않습니다." }
authCommandService.register(SocialAccessToken(socialAccessToken), signUpRequest)

// 혹은 합쳐서
authCommandService.register(
    SocialAccessToken(requireNotNull(socialAccessToken) { "socialAccessToken 가 존재하지 않습니다." }),
    signUpRequest,
)
```

2024-06-23 09:37 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/auth/presentation/spec/AuthControllerSpec.kt
> +                        ],
우와 ㅋㅋㅋㅋ 상상만 했던 코드인데 눈으로 직접보니까 재미있네요 ㅋㅋㅋㅋ
근데 호불호 갈리기 딱좋은 코드일것 같은데 저는 이정도면 아슬아슬하게 호네요

2024-06-23 09:37 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/global/service/ImageService.kt
> +    fun generateImageName(fileName: String?): String {
파일이름이 null일 경우가 있을까요??

2024-06-23 09:37 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/global/service/ImageService.kt
> +                ".${StringUtils.getFilenameExtension(fileName)}"
요런 코드가 예전에 저희 부서에서도 이슈가 된적이 있었는데
유저가 jpeg파일을 png라고 파일 확장자만 바꿔서 업로드 한적이 있는데
그 파일이 대부분 문제 없었지만 일부 서비스에서 읽지를 못하는 경우가 있었어요..!
그래서 파일의 이름에서 확장자를 고대로 따오는게 별로 안전하지는 않은 코드라고 생각이 드네요 ㅋㅋㅋ큐ㅠㅠ

2024-06-23 09:37 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/global/validator/WebPValidator.kt
> +    ): Boolean = p0 == null || Tika().detect(p0.inputStream) == "image/webp"
Tika 객체를 매번 생성하는게 아닌 한번 생성해둔 객체를 재활용하는게 어떨까요??
참고로 Tika().detect는 threadSafe한 메소드라고하네요 ㅋㅋㅋ
https://www.mail-archive.com/user@tika.apache.org/msg03473.html

2024-06-23 09:37 UTC, konempty commented on src/test/kotlin/kr/weit/roadyfoody/auth/application/service/AuthCommandServiceTest.kt
> +                verify(exactly = 0) { imageService.upload(any<String>(), any<MultipartFile>()) }
호출 횟수가 겹치는 애들이 있는데 묶어주면 어떨까요??
```kotlin
                    verify(exactly = 1) {
                        authQueryService.requestKakaoUserInfo(any<SocialAccessToken>())
                        userRepository.existsBySocialId(any<String>())
                        termCommandService.checkRequiredTermsOrThrow(any<Set<Long>>())
                        userRepository.save(any<User>())
                        userAgreedTermCommandService.storeUserAgreedTerms(any<User>(), any<Set<Long>>())
                    }
                    verify(exactly = 0) {
                        imageService.generateImageName(any<String>())
                        imageService.upload(any<String>(), any<MultipartFile>())
                    }
```

2024-06-23 09:37 UTC, konempty commented on src/test/kotlin/kr/weit/roadyfoody/auth/application/service/AuthCommandServiceTest.kt
> +                verify(exactly = 1) { imageService.upload(any<String>(), any<MultipartFile>()) }
여긴 다묶을수 있겠네요 ㅋㅋㅋ

2024-06-23 09:37 UTC, konempty commented on src/test/kotlin/kr/weit/roadyfoody/auth/application/service/AuthIntegrationServiceTest.kt
> +                        s3Template.deleteObject(s3Properties.bucket, imageName)
ㅋㅋㅋㅋ 저번에 테스트 짤때 주석으로 써놨는데
S3의 스펙상 파일삭제는 비동기로 이루어지기 때문에 삭제 요청을 보내도 실제 삭제는 언제될지 알수 없어서
테스트에서는 지우는게 큰 의미가 없어요

2024-06-23 09:37 UTC, konempty commented on src/test/kotlin/kr/weit/roadyfoody/auth/application/service/AuthIntegrationServiceTest.kt
> +        val authCommandService =
요건 코멘트는 아니고 그냥 지식 공유인데
테스트 대상 객체는 다른 객체와는 다르게 sut(System under test)이라는 
정해진 이름으로 지어두는걸 선호하는 회사들도 많아요!
https://en.wikipedia.org/wiki/System_under_test

2024-06-23 09:37 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/auth/application/service/AuthQueryService.kt
> +    fun requestKakaoUserInfo(socialAccessToken: SocialAccessToken) = kakaoClientInterface.requestUserInfo(socialAccessToken)
요기에서 에러가 발생했을때 에러처리 하는 부분이 없는것 같은데
요 API가 실패한다면 잘못된 토큰을 보냈다는 에러 메시지가 필요하지 않을까요??
안그러면 에러 발생시 500 에러가 내려가지 않을까 싶네요 ㅋㅋ큐ㅠㅠ

2024-06-23 09:37 UTC, konempty commented on src/test/kotlin/kr/weit/roadyfoody/auth/application/service/AuthQueryServiceTest.kt
> +            `when`("카카오 Access Token 을 가져오면") {
여기도 실패하는 경우에 대한 에러 처리도 있으면 어떨까 싶네요! ㅋㅋㅋ

2024-06-23 09:37 UTC, konempty commented on src/test/kotlin/kr/weit/roadyfoody/global/service/ImageServiceTest.kt
> +                StringUtils.getFilenameExtension(imageName) shouldBe "null"
StringUtils은 저희가 개발한 코드가 아닌데 저희가 테스트 하는게 뭔가 어색하네요 ㅋㅋㅋ

2024-06-23 09:37 UTC, konempty commented on src/test/kotlin/kr/weit/roadyfoody/auth/presentation/api/AuthIntegrationControllerTest.kt
> +class AuthIntegrationControllerTest(
AuthControllerTest와 AuthIntegrationControllerTest로 나눠서 테스트된 이유가 뭘까요??
둘다 유닛 테스트로 짜거나 둘다 통합테스트로 통일을 하는게 낫지 않을까요?

2024-06-23 09:37 UTC, konempty commented on src/test/kotlin/kr/weit/roadyfoody/user/fixture/UserFixture.kt
> +)
요 두개의 메소드를 하나로 합칠수 있을것 같은데 함치면 어떨까요??

2024-06-23 09:37 UTC, konempty commented on src/test/resources/image/gif_test_img.gif
ㅋㅋㅋㅋ 요렇게 테스트용 리소스는 올리지 않고 테스트 할때 동적으로 생성하는게 좋아요!
gif는 좀 어렵지만 jpg나 png는 가능할거예요!

2024-06-23 09:38 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/auth/exception/UserAlreadyExistsException.kt
> +    ErrorCode.INVALID_REQUEST,
좋은 의견이네요 👍

2024-06-23 09:43 UTC, konempty commented on src/test/kotlin/kr/weit/roadyfoody/auth/presentation/api/AuthIntegrationControllerTest.kt
> +class MockKakaoClient : KakaoClientInterface {
<img width="937" alt="스크린샷 2024-06-23 오후 6 42 41" src="https://github.com/Weit-2nd/roady-foody-server/assets/44064530/24101ad2-cc5a-40b3-94bd-80e1e7301319">
요렇게 mockBean으로 처리하는게 어떨까요??

2024-06-23 09:57 UTC, Unagi-zoso commented on src/test/kotlin/kr/weit/roadyfoody/auth/application/service/AuthQueryServiceTest.kt
> +        val kakaoClientInterface = mockk<KakaoClientInterface>()
좋은 질문 감사합니다.
AuthQueryService 를 테스트 하기 위한 코드라 별도의 빈을 가져오기 보단 모킹을 통해서 일관성있게 구성하면 좋을 것 같아서 그랬습니다.
MockKakaoClient 를 만든 이유는 컨트롤러 단 **통합 테스트** 시 실제 API 를 호출하는 비용이 부담스러워 그 부분을 대체하기 위함이였습니다.

2024-06-23 10:10 UTC, Unagi-zoso commented on src/main/kotlin/kr/weit/roadyfoody/auth/dto/SignUpRequest.kt
> +    val socialLoginType: SocialLoginType = SocialLoginType.KAKAO,
설계한 API 의도대로 요청하지 않는 경우 (ex nickname 폼을 누락)
nickname 은 null 을 허락하지 않는 자료형이라 비즈니스와 관련 없는 예외가 발생하게 됩니다. 따라서 nickname 폼을 누락하더라도 기본적으로 nickname 이 생성되도록 두었습니다. (이후 유효성 검사에서 예외가 발생합니다.)

agreedTermIds 도 비슷한 맥락 입니다. (register() 내 약관 검사에서 예외가 발생합니다.)

socialLoginType 의 경우 현재 카카오 로그인 만을 허용하기에 외부에서 입력을 받지 않습니다. 따라서 기본값을 설정해두었습니다.

2024-06-23 10:20 UTC, Unagi-zoso commented on src/test/kotlin/kr/weit/roadyfoody/auth/presentation/api/AuthIntegrationControllerTest.kt
> +class AuthIntegrationControllerTest(
일단 컨트롤러 테스트 만으로도 대부분의 상황은 테스트가 가능했습니다. (데이터 바인딩, 유효성 검사..). 
이후에 sandbox 에 배포해서 테스트를 해보니 SignUpRequest 객체에 agreedTermIds 가 제대로 전달이 안됐고 이를 판별하는 기능은 service 단에 구현되어 있어서 서비스를 전부 모킹한 기존 컨트롤러 테스트에서 이런 문제를 테스트하지 못했습니다.
지금와서는 기존 컨트롤러 테스트에서 패러미터 바인딩 체크 부분을 추가하면 됐던게 아닌가 생각이 듭니다만 슬슬 프로젝트에서 통합테스트 관련한 코드가 보여 이참에 이런식으로 해결해보면 좋지 않을까 생각이 들어 적어보았습니다.

2024-06-23 10:31 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/auth/dto/SignUpRequest.kt
> +    val socialLoginType: SocialLoginType = SocialLoginType.KAKAO,
> nickname 은 null 을 허락하지 않는 자료형이라 비즈니스와 관련 없는 예외가 발생하게 됩니다.

제 기억에는 HttpNotReadable 대충 요런 이름의 에러가 발생했던것 같은데
그 에러를 잡아서 ${변수명}은 null일수 없습니다
라는 에러를 내리면 비지니스와 관련있는 에러로 처리가능하지 않을까요??

2024-06-23 10:32 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/auth/dto/SignUpRequest.kt
> +    val socialLoginType: SocialLoginType = SocialLoginType.KAKAO,
조금 찾아보니까 제 기억과 비슷한 코드가 잇네요

https://yeongchan1228.tistory.com/m/133

2024-06-23 10:38 UTC, Unagi-zoso commented on src/main/kotlin/kr/weit/roadyfoody/global/service/ImageService.kt
> +    fun generateImageName(fileName: String?): String {
정상적인 서비스 환경에선 문제가 없을듯 하네요.
테스트 환경에서 MockMultipartFile 는 originalFilename 이 Nullable 해서 저렇게 두었는데 StandardMultipartFile 에선 문제 없는것으로보입니다. 
이 부분은 고치겠습니다

2024-06-23 11:56 UTC, Unagi-zoso commented on src/test/resources/image/gif_test_img.gif
혹시 이유를 알 수 있을까요?
정적 데이터 IO 비용을 의식해서 인가요??

2024-06-23 12:08 UTC, konempty commented on src/test/resources/image/gif_test_img.gif
저렇게 테스트를 위한 리소스를 추가하다보면 프로젝트의 크기가 프로덕션 코드와 리소스로 인해 커지는게 아니라 테스트 리소스로 인해 커질것 같아서 말씀드렸습니다~!

2024-06-23 16:29 UTC, Unagi-zoso commented on src/test/kotlin/kr/weit/roadyfoody/auth/application/service/AuthIntegrationServiceTest.kt
> +        afterTest { clearAllMocks() }
일단 제 코드에서 해당 부분을 제거하면 테스트에서 실패합니다.

제가 파악하고 있는 것으론 현재 코드는 Spec 내부에서 변수들을 선언했습니다.
제가 알기로 Kotest 의 Spec 단 한 번만 생성되어(기본설정) Spec 내 테스트에서 사용되는 것으로 알고 있습니다.  따라서 한 번 생성된 mock 객체를 반복해서 사용하고 verify(exactly = 1) 을 하면 실패하게 됩니다. (초기화 되지 않아 중첩되기 때문)

mockk 자동 초기화는 제가 잘 모르는 부분이라 좀 더 공부해보겠습니다!

2024-06-23 17:35 UTC, Unagi-zoso commented on src/test/kotlin/kr/weit/roadyfoody/auth/application/service/AuthIntegrationServiceTest.kt
> +                        s3Template.deleteObject(s3Properties.bucket, imageName)
아하 그렇군요!
일단 저 부분을 제거하면 bucket 비어있지 않다고 deleteBucket() 이 실패합니다.
저 부분이 있더라도 deleteBucket() 이 실행되는 시점에 deleteObject() 가 완료되지 않아 또 deleteBucket() 이 실패할 수도 있다는 말씀이신가요?

2024-06-24 06:24 UTC, jifrozen0110 commented on src/test/kotlin/kr/weit/roadyfoody/auth/application/service/AuthQueryServiceTest.kt
> +        val kakaoClientInterface = mockk<KakaoClientInterface>()
아하 알겠습니다!

2024-06-24 06:30 UTC, jifrozen0110 approved these changes

2024-06-24 06:30 UTC, jifrozen0110 commented on src/test/kotlin/kr/weit/roadyfoody/auth/application/service/AuthIntegrationServiceTest.kt
> +        afterTest { clearAllMocks() }
오호 그렇군요 저도 잘 몰라서 여쭤봤습니다. 감사합니다.

2024-06-24 09:34 UTC, konempty commented on src/test/kotlin/kr/weit/roadyfoody/auth/application/service/AuthIntegrationServiceTest.kt
> +                        s3Template.deleteObject(s3Properties.bucket, imageName)
아하 deleteBucket을 위한 코드라면 있어야 합니다!
저도 제 코드에 그것때문에 삭제코드 넣어놓고 그렇게 해야 한다는걸 잊고있었네요 ㅋㅋㅋㅋ

2024-06-24 09:39 UTC, konempty commented on src/test/kotlin/kr/weit/roadyfoody/auth/presentation/api/AuthIntegrationControllerTest.kt
> +class AuthIntegrationControllerTest(
으흠 이슈가 잘이해안되는데 일단 제가 이해한대로 답변을 드리자면
서비스에서 필수여부를 판단하고 있었다면 그건 컨트롤러의 역할이 아니라 서비스의 역할로 잡으신것 같은데
그렇다면 컨트롤러 테스트에서 확인할게 아니라 서비스 테스트에서 확인해야하는거 아닐까요..??

2024-06-24 12:04 UTC, Unagi-zoso commented on src/test/kotlin/kr/weit/roadyfoody/auth/presentation/api/AuthIntegrationControllerTest.kt
> +class AuthIntegrationControllerTest(
그렇네요. 제가 좀 오용한 듯 하네요. 
저의 원래 의도는 SignUpRequest 객체를 제대로 바인딩 하는지를 확인하기 위해서 였는데 이를 위해 통합테스트를 할 필요는 없어보이네요. 
이 부분은 제거하고 다른 부분에서 보완하겠습니다.

2024-06-24 15:34 UTC, konempty requested changes
정말 고생이 많으시네요 ㅠㅠ
하지만 코멘트 할게 조금남았는데 진짜 조금만더 수정 부탁드립니다..!

2024-06-24 15:34 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/auth/dto/SignUpRequest.kt
> +    val socialLoginType: SocialLoginType = SocialLoginType.KAKAO,
아하 ㅠㅠ notNull을 제대로 쓰기위해 모두가 nullable이 되어버렸군요
이게 이전 코드보다 더 좋지 못한 코드가 되어버린것 같아서 슬프네요

2024-06-24 15:34 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/auth/application/service/AuthQueryService.kt
> +        }
제 처음 의도는 에러 코드에 따른 에러의 분기였는데
모든 에러를 잡아서 InvalidTokenException으로 내리는군요
일단은 요렇게 가시죠

2024-06-24 15:34 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/auth/presentation/api/AuthController.kt
> +        @Valid signUpRequest: SignUpRequest,
@ RequestBody를 붙혀야 하지 않을까요..??

2024-06-24 15:34 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/auth/dto/SignUpRequest.kt
> +    val profileImage: MultipartFile?,
<img width="283" alt="스크린샷 2024-06-25 오전 12 06 25" src="https://github.com/Weit-2nd/roady-foody-server/assets/44064530/c7b25e3e-c4a2-46fc-9e77-bc3fe0a6f83a">

사진 크기에 대한 validation이 있으면 어떨까요??

2024-06-24 15:34 UTC, konempty commented on src/test/kotlin/kr/weit/roadyfoody/auth/application/service/AuthIntegrationServiceTest.kt
> +            )
authQueryService 요거 하나를 목킹해서 AuthCommandService에 주입하기위해 불필요한 빈들을 주입받는데
그런 의도라면 아래의 코드처럼 mockkBean으로 처리하면 깔끔하게 해결됩니다~!

<img width="920" alt="스크린샷 2024-06-25 오전 12 14 29" src="https://github.com/Weit-2nd/roady-foody-server/assets/44064530/fe334305-ab0c-4b07-a70b-e2d89145d7ef">

2024-06-24 15:34 UTC, konempty commented on src/test/kotlin/kr/weit/roadyfoody/global/utils/MimeUtilsTest.kt
> +                then("${WEBP.getStrValues()} 이미지 MIME 타입을 반환한다.") {
ㅋㅋㅋㅋ... 요건 그냥 "WEBP 이미지 파일을 전달하면" 요런식으로 하드코딩 해도 괜찮았을것 같아요

2024-06-24 15:34 UTC, konempty commented on src/test/kotlin/kr/weit/roadyfoody/auth/application/service/AuthCommandServiceTest.kt
> +            every { imageService.generateImageName(any<MultipartFile>()) } returns UUID.randomUUID().toString()
imageService.generateImageName 메소드는 모킹하지 않고도 가능하지 않을까 싶은데 아래 사진처럼 imageService를 mockk이 아닌 spyk로 선언하면 어떨까요?

<img width="912" alt="스크린샷 2024-06-25 오전 12 30 23" src="https://github.com/Weit-2nd/roady-foody-server/assets/44064530/a83393aa-db7c-4ca1-b418-a5a4e92c0cb2">

2024-06-24 15:36 UTC, konempty commented
그리고 한가지 안타까운건
제가 학생분들이나 취준생분들 코드에 리뷰를 하다보면 코드 정리에 너무 집중을 한 나머지
정도를 넘어선 오버엔지니어링을 하시는 분들이 있는데 주열님 코드에서 간간히 보여서 너무 안타깝네요 ㅠㅠㅠ
이게 제가 말로 설명할수 없고 갠취의 영역이라 말씀드리기 까다로운데 주열님이라면 금방 적정수준의 감을 잡으실거라 믿습니다..!

2024-06-24 15:46 UTC, Unagi-zoso commented on src/main/kotlin/kr/weit/roadyfoody/auth/dto/SignUpRequest.kt
> +    val socialLoginType: SocialLoginType = SocialLoginType.KAKAO,
저도 이걸 좀 고민했는데 기본값을 주지 않고 null 을 허용하지 않는 자료형을 사용할 시
스프링에서 바인딩을 할 때 notnull 자료형에 null 을 넣었다고 예외가 발생하더라구요.
이게 fieldError 라면 저희 중앙예외처리 방식으로 처리가 가능한데 이 경우엔objectError 로 예외가 발생하더라구요.

```
// ExceptionHandler.kt 일부

    private fun MethodArgumentNotValidException.messages(): List<String> {
        return bindingResult.fieldErrors.map { "${it.field}: ${it.defaultMessage.orEmpty()}" }
    }

```

그래서 globalError(ObjectError 콜렉션) 으로 예외 정보를 얻어 반환하면 안될까 싶었는데 objectError 의 경우 어느 필드가 null 이다 라고 추출하기가 힘든 완벽한 영어 문장이 나와 이걸 쓰기가 힘들어보였습니다. 

그래서 null 을 허용하는대신 jakarta 유효성 검사로 필드를 검사하면 fieldError 로 나와
정상적으로 저희 중앙예외처리 방식을 사용할 수 있어서 이 방식을 택하긴 했는데

솔직히 이 방식을 사용하면서 회의감이 많이 들었네요.. 개선할 방법이 있을까요?

개인적으론 기본값을 두던 처음 방식은 어땠을까 하는 생각이 좀 드네요..

2024-06-24 15:48 UTC, Unagi-zoso commented on src/main/kotlin/kr/weit/roadyfoody/auth/dto/SignUpRequest.kt
> +    val socialLoginType: SocialLoginType = SocialLoginType.KAKAO,
https://yeongchan1228.tistory.com/m/133

이 사례를 알려주셨는데 이건 Json 데이터의 경우에 해당되는 예외로 보였습니다.
저의 경우엔 Multipart/form-data 를 사용하고 있어 동적으로 생성자를 찾고 인스턴스를 생성하며 `MethodArgumentNotValidException` 예외가 발생했었네요.

2024-06-24 15:54 UTC, Unagi-zoso commented on src/test/kotlin/kr/weit/roadyfoody/global/utils/MimeUtilsTest.kt
> +                then("${WEBP.getStrValues()} 이미지 MIME 타입을 반환한다.") {
아마 이런 부분을 오버엔지니어링의 요소로 말씀하신게 아닌가 생각이 드네요.
저도 코드를 작성하면서 향후에 안생길지도 모르는 부분에 대해 너무 과하게 대처하려하는게 아닌가 생각이 계속 들었네요..

2024-06-24 15:59 UTC, Unagi-zoso commented on src/main/kotlin/kr/weit/roadyfoody/auth/application/service/AuthQueryService.kt
> +        }
저도 그 부분을 좀 고민을 했었네요.

```
// RestClientConfig.kt 일부
  restClientBuilder
            .requestInterceptor(RetryClientHttpRequestInterceptor())
            .requestFactory(clientHttpRequestFactory())
            .defaultStatusHandler(HttpStatusCode::is4xxClientError) { _, response ->
                log.error("Client Error Code={}", response.statusCode)
                log.error("Client Error Message={}", String(response.body.readAllBytes()))
                throw RestClientException()
            }
            .defaultStatusHandler(HttpStatusCode::is5xxServerError) { _, response ->
                log.error("Server Error Code={}", response.statusCode)
                log.error("Server Error Message={}", String(response.body.readAllBytes()))
                throw RestClientException()
            }
            .build()

```

제가 요청을 해서 400, 500 번대의 응답을 받아도 이 핸들러 부분에서 재킹을 하는 것 같더라구요.

RestClientException 예외에서 실패 시의 정보를 구할 수도 없어 이 부분을 어떻게 동적으로 잘 처리할 수 있을까 고민하다. 대부분의 경우엔 토큰이 유효하지 않을 때가 아닐까 싶어 일단 이렇게 처리해뒀습니다.

2024-06-24 16:00 UTC, Unagi-zoso commented
이 부분은 꼭 제가 저만의 기준을 잘 세워보겠습니다!

2024-06-24 16:17 UTC, Unagi-zoso commented on src/main/kotlin/kr/weit/roadyfoody/auth/presentation/api/AuthController.kt
> +        @Valid signUpRequest: SignUpRequest,
혹시 제가 multipart/form-data 로 받을 예정인데 이 경우 json 역직렬화 같은 과정이 필요없어 @RequestBody 는 없어도 되는 건 아닌가요..?

2024-06-25 01:01 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/auth/presentation/api/AuthController.kt
> +        @Valid signUpRequest: SignUpRequest,
아 멀티 파트니까 requestPart겠네요 ㅋㅋㅋ 
제 의도는 아래의 링크처럼 처리하는걸 생각했는데 안붙혀도 잘 작동하나요??
https://github.com/weIT-1st/Odya-server/blob/4bcdb173573c53ffb3aea2722697474f0f5ded5b/src/main/kotlin/kr/weit/odya/controller/TravelJournalController.kt#L45

2024-06-25 11:01 UTC, Unagi-zoso commented
최대 파일 크기를 검사하는 기능을 추가했습니다.
이 기능을 코드로 테스트하는 건 생략했습니다.
기준을 1MB 로 했는데 동적으로 1MB 의 파일을 생성하는건 이미지 포매팅 과정에서 압축 등을 고려했을 때 
정확하게 만들기 힘들고 생성 비용이 너무 컸습니다.
그래서 개인환경에서 직접 1MB 크기 이상의 파일을 넣어봄으로써 테스트했습니다.
혹시 좋은 방법이 있을까요?

저희 개발환경에서 1MB 이상의 파일을 넣어봤는데 다음 결과가 나왔습니다. 
좀 찾아보니 nginx 나 쿠버네티스 인그레스 설정을 고려해보라고 하네요.

<img width="543" alt="스크린샷 2024-06-25 오후 7 47 58" src="https://github.com/Weit-2nd/roady-foody-server/assets/97292432/af6ee318-c469-4b2f-9d2b-5c256f0ac7a0">

2024-06-25 11:18 UTC, Unagi-zoso commented on src/main/kotlin/kr/weit/roadyfoody/auth/presentation/api/AuthController.kt
> +        @Valid signUpRequest: SignUpRequest,
작동은 잘됐습니다. 제가 원하는 대로 바인딩을 했는데 
non-null 자료형과 저희 프로젝트 중앙예외처리 시스템을 잘 이용하려면
파일과 파일외의 요소는 분리해서 다루는게 좋겠더라구요. (저의 코드에선 텍스트들은 JSON 으로 SignUpRequest, 이미지파일은 MultipartFile 로 분리해 입력 받았습니다.)
현재는 보여주신 코드도 잘 참고해서 적용해뒀습니다.

2024-06-25 13:06 UTC, konempty approved these changes
작업기간보다 리뷰 반영 기간이 더 길었던것 같네요 ㅋㅋㅋ큐ㅠㅠㅠ
앞으로 얼라인이 되어가면서 리뷰는 조금씩 줄지않을까 싶네요
고생하셨구요 코멘트 조금 남겼는데 적용하신뒤 머지 부탁드립니다~!

2024-06-25 13:06 UTC, konempty commented on src/test/kotlin/kr/weit/roadyfoody/auth/presentation/api/AuthControllerTest.kt
> +
iamge가 1MB를 넘으면 어떻게 될지에 대한 테스트도 추가되면 좋을것 같습니다~!

2024-06-25 13:06 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/auth/application/service/AuthCommandService.kt
> +        }
요 두개 터트리는 에러가 같은데 if문을 합치는게 낫지 않을까요??

2024-06-25 13:06 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/auth/presentation/spec/AuthControllerSpec.kt
> +        ],
요 API는 ApiResponse를 정의 안해줘도 클라분들이 안헷갈리실까요??

2024-06-25 13:06 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/global/validator/MaxFileSizeValidator.kt
> +class MaxFileSizeValidator : ConstraintValidator<MaxFileSize, MultipartFile?> {
validator에 대한 테스트도 있으면 좋을것 같아요~!

2024-06-25 13:06 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/global/validator/WebPValidator.kt
> +}
얘도 테스트가 있으면 좋을것 같구요 ㅎㅎ

2024-06-25 13:06 UTC, konempty commented on src/test/kotlin/kr/weit/roadyfoody/auth/fixture/AuthFixture.kt
> +
이미지 생성 로직이 다 동일한것 같은데 굳이 사용용도 별로 나눠둔 이유가 있을까요??

2024-06-25 13:06 UTC, konempty commented on src/test/kotlin/kr/weit/roadyfoody/auth/fixture/AuthFixture.kt
> +): MockMultipartFile = MockMultipartFile(name, originalName, contentType, contentStream)
얘도 쓰임새가 많아보이는데 좀더 보편적으로 사용가능한 이름으로 지어서 다른곳에서 재활용하기 쉽도록 하면 어떨까요??

2024-06-25 13:06 UTC, konempty commented on src/test/kotlin/kr/weit/roadyfoody/support/annotation/ControllerIntegrateTest.kt
> +annotation class ControllerIntegrateTest
얘는 결국 쓰임새가 없어진것 같은데 없애면 어떨까요?? ㅋㅋㅋ

2024-06-25 13:25 UTC, konempty commented
>최대 파일 크기를 검사하는 기능을 추가했습니다.
이 기능을 코드로 테스트하는 건 생략했습니다.
기준을 1MB 로 했는데 동적으로 1MB 의 파일을 생성하는건 이미지 포매팅 과정에서 압축 등을 고려했을 때
정확하게 만들기 힘들고 생성 비용이 너무 컸습니다.
그래서 개인환경에서 직접 1MB 크기 이상의 파일을 넣어봄으로써 테스트했습니다.
혹시 좋은 방법이 있을까요?

저희 개발환경에서 1MB 이상의 파일을 넣어봤는데 다음 결과가 나왔습니다.
좀 찾아보니 nginx 나 쿠버네티스 인그레스 설정을 고려해보라고 하네요.

어후 ㅋㅋㅋ 인그레스가 막고있나보군요
저건 수정해두겠습니다~!

2024-06-25 13:33 UTC, konempty commented
@Unagi-zoso 인그레스 수정완료했습니다~!

2024-06-25 14:00 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/global/client/RestClientConfig.kt
> +        private const val KAKAO_URL = "https://kapi.kakao.com"
요거 지금알았는데 카카오 지도 검색도있어서 카카오 URL이라 쓰면 곤란할것 같아요 ㅋㅋㅋ
좀더 직관적인 이름으로 부탁드려요!

2024-06-25 16:30 UTC, merged