ROFO-63 사용자 거리 이내 가게 조회
Weit-2nd/roady-foody-server pull request #31
Opened 2024-07-08 11:00 UTC by jifrozen0110

### 개요

### 변경사항
- FoodSpotsCustomRepository 생성

1. 사용자 거리 이내 가게 조회 (500m)
2. 1번 + 카테고리 별 조회
3. 가게 이름 조회는 CONTAINS함수가 작동이 안되어 아직 개발 안됐습니다.
- SearchDsl 생성자 : 복잡한 쿼리 관리
- 가게 조회 service : open의 경우
-> true {
영업시간에 맞춰 열렸는지 닫혔는지 확인
}
-> false{
임시 휴무
}

### 테스트
- 테스트 코드 추가여부 O/X O
- 테스트 코드가 추가되지 않았다면 그 이유를 적어주세요.

### 관련 지라 및 위키 링크
 - [JIRA](https://weit-2nd.atlassian.net/browse/ROFO-63) 

### 리뷰어에게 하고 싶은 말

1. 가게 이름 검색이 안되는데 혹시 이전에 작업해보셨거나 짐작 가시는것 있다면 젭알 던져주세요....
2. 테스트 코드 작성중에 특이한 오류를 발견했는데 아시는 분 있으실까요?(코드에 설명하겠습니다!)
3. 현재 샌드박스 서버가 오류가 난것같습니다. 오류 고치면 배포해서 클라 개발자분들께 피드백 받겠습니다.

2024-07-08 11:02 UTC, jifrozen0110 commented on src/test/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepositoryTest.kt
> +                            createTestFoodSpotsFoodCategory(foodSpots = foodSpots[4], foodCategory = foodCategory[0]),
------------------------의문인 부분---------------------------

foodSpots[4] -> foodSpots[0]으로 바꿔주면 오류가 납니다.
왜인지 쿼리를 뜯어보니
foodSpots[0]을 제대로 생성을 못하더군요.(전체 테스트시에만)
각 클래스별로 따로 테스트를 하면 정상적으로 쿼리가 도는데
repository가 통합테스트이고 testcontainers를 통해 실제 환경과 유사한 환경을 제공해줘서 일까요?

deleteAll도 해보고 saveAllAndFlush도 해봤는데 안됐습니다...

2024-07-08 13:48 UTC, konempty requested changes
고생하셨습니다 👍 👍 
딱 적절한 개발 난이도로 개발된것 같아서 좋네요 ㅋㅋㅋ
코멘트 남겨두었으니 피드백 반영 부탁드립니다~!

2024-07-08 13:48 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/DayOfWeek.kt
> +        fun of(num: Int): DayOfWeek = values().first { it.num == num }
kotlin에서 values()는 deprecated대상인데 경고 뜨지않나요..??
<img width="519" alt="스크린샷 2024-07-08 오후 9 19 19" src="https://github.com/Weit-2nd/roady-foody-server/assets/44064530/2555e98c-61c6-4b91-b223-552b07e56538">

2024-07-08 13:48 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsFoodCategoryRepository.kt
> +}
어 빈괄호도 ktlint가 싫어하는 대상인데
혹시 ktlint 안돌리고 계신가요??
저희 컨벤션이 ktlint 돌리는것 인데 플러그인 설치확인부탁드립니다!

2024-07-08 13:48 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/dto/FoodSpotsSearchCondition.kt
> +    @Schema(name = "categoryIds", description = "음식 카테고리 ID 리스트 - 값이 없으면 빈문자열을 보내주세요.", required = false, example = "1,2")
값이 없다면 빈문자열이 아니라 안보내는게 더 맞는 방향이지 않을까요??

2024-07-08 13:48 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/dto/FoodSpotsSearchCondition.kt
> +    val categoryIds: List<Long>?,
convertToCategoryIds의 반환형이 List<Long>니까 nullable일 필요가 없어보이는데 nullable로 선언하신 이유가 있을까요??

2024-07-08 13:48 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/dto/FoodSpotsSearchResponse.kt
> +    val foodCategories: List<String>,
각 필드 설명을 붙혀두는게 좋지 않을까요??

2024-07-08 13:48 UTC, konempty commented on src/test/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepositoryTest.kt
> +                expected.get(2).name shouldBe "Food Spot 3 - 500m"
여기는 그냥 expected[0].name 해도 되지않나요??
get메소드로 가져오는 이유가 궁금합니다~!

2024-07-08 13:48 UTC, konempty commented on src/test/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepositoryTest.kt
> +                            createTestFoodSpotsFoodCategory(foodSpots = foodSpots[4], foodCategory = foodCategory[0]),
으흠 0번은 좌표 기준 800m떨어진 곳이라 검색이 안되는거 아닐까요??
<img width="954" alt="스크린샷 2024-07-08 오후 9 12 51" src="https://github.com/Weit-2nd/roady-foody-server/assets/44064530/71eaf1e0-b18c-4601-b9b3-642ddfdc7f7b">

2024-07-08 13:48 UTC, konempty commented on src/test/kotlin/kr/weit/roadyfoody/search/foodSpots/application/FoodSpotsSearchServiceTest.kt
> +                    foodSpotsSearchResponses.items.shouldHaveSize(0)
foodSpotsSearchResponses.items.shouldBeEmpty()가 좀더 의도를 잘 나타낼것 같습니다~!

2024-07-08 13:48 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/common/domain/query/QueryDomainDsl.kt
> +                "{0}  || '' = 'TRUE'",
으흠 요 쿼리는 무슨 의도인지 이해가 잘 안가는데 설명가능하실까요..??

2024-07-08 13:48 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/common/domain/query/QueryDomainDsl.kt
> +    }
얘는 this를 사용안하는것 같은데 확장함수로 작성된 이유가 있을까요??

2024-07-08 13:48 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/common/domain/query/QueryDomainDsl.kt
> +    ): Predicate {
얘도 this를 사용안하네요 ㅋㅋㅋ..

2024-07-08 13:48 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/FoodSpots.kt
> +    @OneToMany(mappedBy = "foodSpots", cascade = [CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REMOVE], orphanRemoval = true)
아하 ㅋㅋ... 카스케이드 걸면 골치아픈일이 많이벌어져서 카스케이드는 안쓰는걸 추천드려요

2024-07-08 13:48 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
> +                            },
요걸 좀더 코틀린의 문법을 적극적으로 활용하면 아래와 같이 가능합니다~!
```kotlin
filteringFoodSpotIds.takeIf { categoryIds.isNotEmpty() }?.let {
    entity(FoodSpots::class).foodSpotIdIn(it)
}
```
실제로 저는 회사에서 이렇게 쓰는걸 선호하는데 요건 단순히 가능성만 보여드린거라 적용 안하셔도 좋습니다~!

2024-07-08 13:48 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
> +
이거 customExpression으로 사용하셔서 그럴거예요 ㅋㅋㅋ
function으로 써야 제대로 작동하는걸로 기억해요
```kotlin
                         val containsNameFunction =
                                function(
                                    Int::class,
                                    "CONTAINS",
                                    listOf(
                                        Expressions.stringLiteral(path(FoodSpots::name).toString()),
                                        Expressions.stringLiteral(wildCardName),
                                    ),
                                )
```

2024-07-08 13:48 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/common/domain/query/QueryDomainDsl.kt
> +
DSL를 적극적으로 활용하는건 좋은데 혹시 DSL로 만드시는 기준이 있으신건가요??
요건 꽤 짧은 코드인데 DSL화 했고 RepositoryImpl에서는 좀더 긴 코드인데도 DSL화 하지 않은게 있어서 궁금합니다!

2024-07-08 13:48 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
> +    }
<img width="479" alt="스크린샷 2024-07-08 오후 10 37 17" src="https://github.com/Weit-2nd/roady-foody-server/assets/44064530/5cf07f41-8638-4167-95f0-c2a94607abdd">
요거 앞으로 많이 쓰일것 같은데 KotlinJDSLUtil에 확장함수로 만들어 두는게 어떨까요??

2024-07-08 13:48 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
> +                                .greaterThanOrEqualTo(categoryIds.size.toLong()),
이부분의 의도가 이해가 잘안되는데 의도를 자세하게 설명해주실수 있으실까요??

2024-07-08 13:48 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/application/FoodSpotsSearchService.kt
> +        val format: DateTimeFormatter = DateTimeFormatter.ofPattern("HH:mm")
어디는 자료형을 명시하고 어디는 생략 하시는것 같은데 요것도 기준이 있으신걸까요??

2024-07-08 13:48 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/presentation/spec/FoodSpotsSearchControllerSpec.kt
> +        @ParameterObject @ModelAttribute @Valid foodSpotsSearchCondition: FoodSpotsSearchCondition,
@ ModelAttribute를 붙히시는 이유가 궁금합니다!

2024-07-08 13:48 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/presentation/spec/FoodSpotsSearchControllerSpec.kt
> +        @ParameterObject @ModelAttribute @Valid foodSpotsSearchCondition: FoodSpotsSearchCondition,
오 그리고 ParameterObject는 처음 보는 어노테이션인데 너무 좋네요! ㅋㅋㅋㅋ
다른곳에도 적용해야겠어요

2024-07-08 13:48 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
한가지 궁금한게 있는데 지도의 좌표 검색 방식이 여러가지가 있는데 그걸 찾아보시고
DB에서 쿼리 검색하는게 좋을것 같아서 선택하신건지 궁금합니다!
성능을 위해서 레디스를 쓰거나 검색에 최적화된 ES를 사용하는 예제가 많거든요 ㅋㅋㅋ

참고로 지금 구현 방식도 정말 훌륭하고 짧은 프로젝트 기간내에 가능한 적절한 난이도의 구현이라고 생각합니다!

2024-07-08 14:38 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/DayOfWeek.kt
> +        fun of(num: Int): DayOfWeek = values().first { it.num == num }
엇 경고가 빨간줄이 아니라 형광펜으로 떠서 못알아봤습니다! 수정하겠습니다

2024-07-08 14:45 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsFoodCategoryRepository.kt
> +}
klint 플러그인 설치하고 설정도 완료하였는데 이상하네요...
![image](https://github.com/Weit-2nd/roady-foody-server/assets/62784314/75ae418b-4c0f-4440-a276-fe227a996345)

혹시 gradle 명령어 돌려야하는걸까요?

2024-07-08 14:51 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/dto/FoodSpotsSearchCondition.kt
> +    val categoryIds: List<Long>?,
기존에는 query dto로 클라이언트에서 값을 받았는데
List값을 더 쉽게 값을 받기 위해 condition dto를 추가하였는데
그 후 query dto 수정을 안하여 nullable상태로 남아있었습니다.
수정하겠습니다!

2024-07-08 15:29 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/common/domain/query/QueryDomainDsl.kt
> +
RepositoryImpl에 있는 좀 더 긴 코드는 name관련 쿼리인데 동작을 하지 않아 우선 impl안에 있는것이고 동작하면 DSL로 옮길 예정입니다!

2024-07-08 15:29 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/common/domain/query/QueryDomainDsl.kt
> +                "{0}  || '' = 'TRUE'",
정말 이 쿼리 때문에 고생하였는데요...
왜인지는 모르겠지만
```
 val sdoWithinDistance =
            Expressions.customExpression(
                String::class,
                sdoWithinDistanceClause,
                listOf(
                    Paths.path(FoodSpots::point),
                ),
            )
```

sdoWithinDistanceClause의 반환값이 'TRUE' 와 'FALSE' 문자열값인데
이걸 바로 = 'TRUE'로 비교하면 작동이 안돼
Expression으로 문자열을 얻고
이를 predicate로 비교하는 식으로 하였습니다.
근데 또 단순하게
"{0}   = 'TRUE'",
이렇게 하면 작동이 안돼
구글링을 해보니
"{0}  || '' = 'TRUE'",
이렇게 하라는 말이 적혀있어 적용하였는데 작동하였고
실제 sql 쿼리에서도 {0}  || '' = 'TRUE' 적어도 작동하여서 적용하였습니다.

2024-07-08 15:29 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/FoodSpots.kt
> +    @OneToMany(mappedBy = "foodSpots", cascade = [CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REMOVE], orphanRemoval = true)
아 그렇군요!
혹시 OperationTime의 경우 카스케이드 설정을 통해 부모와 생명주기를 같이 관리하면 더 좋을것으로 생각이 드는데
카스케이드는 기준에 따라 쓰이고 안쓰이는건지 아니면 기준없이 지양하는건지 궁금합니다!

2024-07-08 15:29 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/common/domain/query/QueryDomainDsl.kt
> +    }
맞네요! 수정하겠습니다!

2024-07-08 15:29 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
> +                            },
와 정말 코틀린스럽네요! 바로 반영하겠습니다

2024-07-08 15:29 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
> +    }
넵 반영하겠습니다!

2024-07-08 15:30 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/application/FoodSpotsSearchService.kt
> +        val format: DateTimeFormatter = DateTimeFormatter.ofPattern("HH:mm")
자바 버릇이 잠깐씩 튀어나오네요! 수정하겠습니다.

2024-07-08 15:48 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
> +                                .greaterThanOrEqualTo(categoryIds.size.toLong()),
예를 들어,
카테고리 포장마차, 붕어빵, 술, 분식

가게 1 포장마차, 붕어빵
가게 2 포장마차, 분식
가게 3 포장마차, 술
가 있으면 사용자가
포장마차 && 분식 카테고리별로 가게를 보고싶은데

having 조건이 없으면
가게 1, 가게 2, 가게.3 모두 반환됩니다.

연산 순서로 설명드리면

where로
가게 1 - 포장마차
가게 2 - 포장마차
가게 2 - 분식
가게 3 - 포장마차
이렇게 반환될때

group by를 통해

가게 1 1개
가게 2 2개
가게 3 1개

가 되고 이를 having을 통해 >=2 이상이 되니
가게 2만 반환됩니다.

2024-07-08 15:57 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/presentation/spec/FoodSpotsSearchControllerSpec.kt
> +        @ParameterObject @ModelAttribute @Valid foodSpotsSearchCondition: FoodSpotsSearchCondition,
쿼리 파라미터를 dto로 받기 위해 ModelAttribute를 적용하였습니다.
근데 이슈가 하나 있었습니다. ModelAttribute만 적용하면
swagger상에서 requestBody로 입력하는 창이 생기는 이슈였는데요. (https://github.com/springdoc/springdoc-openapi/issues/119) (swagger상에서 ModelAttribut가 rest 스럽지 않아 이슈를 반영해주진 않는다고 합니다...)

이를 해결하기 위해 ParameterObject를 사용하였습니다.

2024-07-08 16:13 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
우선 제가 개발이 늦어진부분과 추후 개발할 부분이 많다는 점에서 oracle 쿼리를 사용하기로 결정하였습니다.
redis는 메모리에 저장하는거라 가게 데이터를 전부 저장하기에 무리가 있을거라 판단하였고
ES의 경우 사용해보고 싶지만 한번도 사용해본 경험이 없어 러닝커브가 있다고 판단하였습니다.

2024-07-08 16:19 UTC, jifrozen0110 commented on src/test/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepositoryTest.kt
> +                            createTestFoodSpotsFoodCategory(foodSpots = foodSpots[4], foodCategory = foodCategory[0]),
헉 세상에 3시간동안 찾았는데.....감사합니다

2024-07-08 16:38 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/FoodSpots.kt
> +    @OneToMany(mappedBy = "foodSpots", cascade = [CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REMOVE], orphanRemoval = true)
허억...CascadeType를 삭제해줬더니 자식 생명주기 관리가 불가능하여
FoodSpotsSearchService에서
it.foodSpotsOperationHours
it.foodCategories 같은게 사용이 불가능합니다.

그래서
foodCategory=FoodCategoryRepository.findBySpotId(id);
이런식으로 명시적으로 불러와서 사용해야하는데

위와 같이 작업하면 배치사이즈로 oneTomany객체를 같이 들고온 장점이 사라지는건 아닐까요?

2024-07-08 17:34 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
> +
function으로 해봤는데
CASE SDO_GEOM.RELATE(fs1_0.name, 'CONTAINS', '%100m%') WHEN 'FALSE' THEN 0  ELSE 1  END>0)
쿼리를 확인해보니 기존이랑 같은 오류가 나옵니다...
Contains 문자열 비교 함수가 아닌 SDO_GEOM.RELATE 함수로 되는것같습니다

혹시 몰라
val containsNameFunction =
            function(
                Int::class,
                "INSTR",
                listOf(
                    path(FoodSpots::name),
                    Expressions.stringLiteral(wildCardName),
                ),
            )
INSTR함수로 시험삼아 써봤는데 이건 정상 작동합니다...

2024-07-08 19:13 UTC, Unagi-zoso commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsFoodCategoryRepository.kt
> +}
ktlint 플러그인 버전마다 다른 부분이 있지 않나요?

2024-07-09 03:10 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsFoodCategoryRepository.kt
> +}
ktlint 버전 업데이트 부탁드립니다~!
UI보니까 아직 구버전 사용중이신것 같네요 ㅋㅋㅋ

2024-07-09 03:10 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsFoodCategoryRepository.kt
> +}
그리고 gradle 명령어도 가끔 돌려주시면 좋습니다!

2024-07-09 03:24 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/FoodSpots.kt
> +    @OneToMany(mappedBy = "foodSpots", cascade = [CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REMOVE], orphanRemoval = true)
> 카스케이드는 기준에 따라 쓰이고 안쓰이는건지 아니면 기준없이 지양하는건지 궁금합니다!

일단 저는 개인적으로도 저걸로 고통을 받아봐서 개인 프로젝트에서는 이유 불문 쓰는걸 지양하는 편이구요
DBA분들도 보통 어지간한 요청(ex. 쓸대없이 복잡한 쿼리, 사이즈가 과하게 큰 컬럼 등 DB 성능에 이슈를 주는 요청)은 서비스에서 진짜 꼭 필요하다고 하면 다들어주시는데 딱 2가지 절대 반대하시는게 있어요
1. DB 프로시져
2. FK와 같이 거는 카스케이드

카스케이드를 DDL로 요청드리면 아래와 같이 답변이 날라옵니다 ㅋㅋㅋ..
<img width="623" alt="스크린샷 2024-07-09 오후 12 17 38" src="https://github.com/Weit-2nd/roady-foody-server/assets/44064530/0ae3fa02-e487-433f-9a8e-46ad1182754b">

따라서 저는 왠만하면 제외하는걸 선호합니다!

2024-07-09 03:25 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/FoodSpots.kt
> +    @OneToMany(mappedBy = "foodSpots", cascade = [CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REMOVE], orphanRemoval = true)
>it.foodSpotsOperationHours
it.foodCategories 같은게 사용이 불가능합니다.

요건 다른 이슈인것 같아요..! 카스케이드를 땐다고 해서 oneToMany를 못쓰는 케이스는 못들어본것같아요

2024-07-09 03:33 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
> +
오호 그렇다면 inSTR을 쓰셔도 되지 않을까요??
혹시 InSTR은 Context Index를 못타는 함수인가요..?

2024-07-09 03:43 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/presentation/spec/FoodSpotsSearchControllerSpec.kt
> +        @ParameterObject @ModelAttribute @Valid foodSpotsSearchCondition: FoodSpotsSearchCondition,
@ ModelAttribute를 안붙혀도 쿼리파람을 DTO로 받는데 문제 없지 않나요??

2024-07-09 03:51 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
오호 충분히 고민을 해보셨던것 같고 의도또한 명확한것 같아서 너무 좋습니다~! ㅋㅋㅋ
참고로 가게 정보는 레디스에 충분히 올릴수 있는정도의 데이터예요!
아래 링크는 **가상면접사례로 배우는 대규모 시스템 기초 2**의 미리 보기 자료인데 마침 1장의 내용과 같은 고민을 하신것 같네요 ㅋㅋㅋㅋ

https://blog.insightbook.co.kr/wp-content/uploads/2024/01/ebafb8eba6acebb3b4eab8b0-eb8c80eab79cebaaa8-ec8b9cec8aa4ed859c-ec84a4eab384-eab8b0ecb488-2-ecb59ceca285.pdf

2024-07-09 03:57 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
> +                                .greaterThanOrEqualTo(categoryIds.size.toLong()),
아하 카테고리 검색으로 여러개가 들어오면 그걸 전부 만족하는 결과를 도출하는거였군요 ㅋㅋㅋㅋ
저는 예를 들어 분식, 붕어빵 카테고리를 사용자가 선택하면
분식집 or 붕어빵인 집을 찾아서 내려준다로 생각했거든요
하지만 지언님의 예시를 보니 and 연결하는게 더 맞는 방향인것 같네요 ㅋㅋㅋ
요건 요렇게 가시고 나중에 문제가 되거나 or로 묶는게 맞겠다는 의견이 나오면 그때 수정하도록 하시죠

2024-07-09 04:21 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/domain/FoodSpots.kt
> +    @OneToMany(mappedBy = "foodSpots", cascade = [CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REMOVE], orphanRemoval = true)
아하! 개인적인 케이스까지 공유해주셔서 감사합니다! 너무 잘 이해했습니다.

2024-07-09 04:21 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsFoodCategoryRepository.kt
> +}
넵 확인하였습니다!

2024-07-09 04:21 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
> +
아 네네 index를 못타는 함수입니다...

2024-07-09 04:21 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
> +                                .greaterThanOrEqualTo(categoryIds.size.toLong()),
넵 알겠습니다!

2024-07-09 04:21 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
와 너무 도움이 되는 내용입니다. 마침 책이 있어 읽어봤는데
redis에서 geoHash랑 사업장 id를 저장해두고 캐싱하면 정말 좋을것같네요!
추후에 기회가되면 추가적으로 적용해보겠습니다!
좋은내용 공유해주셔서 감사합니다.

2024-07-09 05:01 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/presentation/spec/FoodSpotsSearchControllerSpec.kt
> +        @ParameterObject @ModelAttribute @Valid foodSpotsSearchCondition: FoodSpotsSearchCondition,
ModelAttribute도 requestParam처럼 생략할수있지만 명시적으로 어노테이션을 붙여주는것을
권장한다고 들어 붙였습니다.

2024-07-09 07:02 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
> +                        and(
요거 whereAnd라는 메소드 하나로 묶는게 나을것 같아요 ㅋㅋㅋ

2024-07-09 07:02 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
> +
혹시 그러면 myStringContains라는 가상의 함수를 선언하고 실제로 그 함수를 스탠다드 function과 연결되도록 해봐주실수 있나요??
아래 링크 참고 부탁드립니다!
https://www.inflearn.com/questions/1096265/hibernate-6-custom-%ED%95%A8%EC%88%98-%EB%93%B1%EB%A1%9D-%EB%B0%A9%EB%B2%95-%EA%B3%B5%EC%9C%A0?commentId=316217

2024-07-09 07:02 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/presentation/spec/FoodSpotsSearchControllerSpec.kt
> +        @ParameterObject @ModelAttribute @Valid foodSpotsSearchCondition: FoodSpotsSearchCondition,
오호 그런가요..?
저는 ModelAttribute를 Spring MVC할때 사용하고 RestController와 상관이 없는 어노테이션이라고 알고있거든요
지언님이 그렇다면 저도 그렇게 알고있겠습니다 ㅋㅋㅋㅋ

2024-07-09 07:16 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/presentation/spec/FoodSpotsSearchControllerSpec.kt
> +        @ParameterObject @ModelAttribute @Valid foodSpotsSearchCondition: FoodSpotsSearchCondition,
> ModelAttribute를 Spring MVC할때 사용하고 RestController와 상관이 없는 어노테이션


넵 맞습니다!
해당 용도와 다른 용도로 쓴거긴한데
ModelAttribute 의 역할을
dto를 쿼리 파라미터로 쓸때 ModelAttribute로 명시적 어노테이션을 표시한다 라는 역할로 지정하여 사용하였습니다.

2024-07-09 14:35 UTC, konempty requested changes

2024-07-09 14:35 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/common/domain/query/QueryDomainDsl.kt
> +                "{0}  || '' = 'TRUE'",
대충 어떤 이슈인지는 알아서 어떻게든 회피해보려고 저도 나름 노력해봤는데 
지금 상황 이상으로 좋게는 어렵네요 ㅋㅋㅋ...
어차피 '' = 'TRUE'는 쿼리 옵티마이저에 의해 무시가 될테니 지금 상태로 두는게 나을것 같습니다

2024-07-09 14:35 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
> +    }
여기 중복되는 코드가 많이보이는데 아래와 같이 중복되는 코드를 묶어보는건 어떨까요??
```kotlin
        executor.findAll {
            jpql(SearchDsl) {
                val baseQuery =
                    selectDistinctNew<Long>(
                        path(FoodSpotsFoodCategory::foodSpots)(FoodSpots::id),
                    ).from(
                        entity(FoodSpotsFoodCategory::class),
                    )

                if (categoryIds.isNotEmpty()) {
                    baseQuery
                        .where(
                            entity(FoodSpotsFoodCategory::class).foodCategoryIn(categoryIds),
                        ).groupBy(
                            path(FoodSpotsFoodCategory::foodSpots)(FoodSpots::id),
                        ).having(
                            count(path(FoodSpotsFoodCategory::foodCategory)(FoodCategory::id))
                                .greaterThanOrEqualTo(categoryIds.size.toLong()),
                        )
                } else {
                    baseQuery
                }.orderBy(
                    path(FoodSpotsFoodCategory::foodSpots)(FoodSpots::id).desc(),
                )
            }
        } as List<Long>
```
그리고 if문을 써도 되는곳에 when을 쓰신것 같은데 이유가 있을까요??

2024-07-09 14:35 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
> +    }
아 그리고 여기도 findList 확장함수를 써주시면 좋을것 같아요!

2024-07-09 14:35 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/application/FoodSpotsSearchService.kt
> +    @Transactional
요 트랜잭션 내부에서는 Write하는 코드가 안보이는데
```kotlin
    @Transactional(readOnly = true)
```
으로 효율적으로 선언하는게 어떨까요??

2024-07-09 14:35 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/dto/FoodSpotsSearchCondition.kt
> +        return FilteringConverter.convertToCategoryIds(categoryIds!!)
그리고 코드를 보다보니까 느낀점인데
https://example.com?categoryIds=1,2,3 이렇게 받아서 사용하시는걸 의도하신것 같은데
굳이 클라에서 리스트를 스트링으로 풀었다가 서버가 다시 파싱하는것보다
그냥
https://example.com?categoryIds=1&categoryIds=2&categoryIds=3
이렇게 해서 클라도 보내기 쉽고 서버에서도 파싱하지 않고 리스트로 받는게 낫지않을까요..??
혹시 이렇게 DTO로 받으면 위와 같은 방식을 쓰기 어려운가요?

2024-07-09 14:35 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/dto/FoodSpotsSearchResponse.kt
> +    TEMPORARILY_CLOSED,
오 Enum에도 설명을 걸수 있군요 ㅋㅋㅋ
처음알았네요

2024-07-09 14:35 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/dto/FoodSpotsSearchResponse.kt
> +)
음식점 등록일자 같은것도 혹시나 모르니까 내려주면 좋을것 같습니다~!

2024-07-09 14:35 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/presentation/api/FoodSpotsSearchController.kt
> +}
여기에 리뷰 달았던것 같은데 안달려있네요 ㅋㅋㅋ..
이미 /api/v1/food-spots라는 Path를 사용중인 FoodSpotsController가 있는데
같은 path를 공유하는 별도의 컨트롤러를 만든 이유가 있으실까요??

2024-07-09 14:39 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
> +    }
when이 더 가독성이 좋아보여서 선택하였습니다!

2024-07-09 14:39 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/application/FoodSpotsSearchService.kt
> +    @Transactional
넵 수정하겠습니다!

2024-07-09 14:44 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/dto/FoodSpotsSearchCondition.kt
> +        return FilteringConverter.convertToCategoryIds(categoryIds!!)
아 개인적으로 프로젝트했을때 같이했던 클라 개발자가 a=APT:PRE:OPST:OBYG
이런식으로 문자열 구분자를 통해 데이터를 보내는걸 선호해서 적용하였습니다!

2024-07-09 14:49 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/dto/FoodSpotsSearchResponse.kt
> +)
네엡!~

2024-07-09 14:51 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/dto/FoodSpotsSearchCondition.kt
> +        return FilteringConverter.convertToCategoryIds(categoryIds!!)
ㅋㅋㅋ 그렇군요 라이브러리 따라 편한게 다르긴한데
제가 안드쪽 라이브러리를 보니까 제가 추천한 방식을 더 편하게 느낄거예요 ㅋㅋㅋ

2024-07-09 14:52 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/dto/FoodSpotsSearchCondition.kt
> +        return FilteringConverter.convertToCategoryIds(categoryIds!!)
넵 수정하겠습니다!

2024-07-09 16:13 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/presentation/api/FoodSpotsSearchController.kt
> +}
이 부분은 고민하였는데 search 패키지안에 주소검색과 관광지검색이 모두 있기 때문에
가게 검색도 따로 컨트롤러를 통해 search 안에 넣어놨습니다.

대신 좀 아시운점은 SearchController로 만들어서
/search api로 통일하고
각 메서드에 따라 /address /food-spots /tour 로
하는 것이 더 가독성이 좋았을거라는 후회는 하고있습니다 😭

2024-07-09 16:14 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
> +
이 부분 진행하였는데 계속 해결은 안되네요...
우선 진행한 부분까지만 올려두겠습니다!

2024-07-09 21:01 UTC, Unagi-zoso approved these changes
고생 많이 하신게 느껴지네요.. 좋은 결과물 잘 봤습니다! 👍  
제가 잘 모르는 부분이 많아 리뷰가 늦어졌네요.
복잡한 쿼리에 RepositoryTest 까지 해야하니 스트레스가 꽤 컸을 것 같아요.
궁금한 부분이 조금 있어 여쭤봤습니다!

2024-07-09 21:01 UTC, Unagi-zoso commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
> +            when (categoryIds.isNotEmpty()) {
요 부분은 if 문으로 바꾼다면 depth 가 좀 줄 수 있을 것 같은데
아마 이편이 보기 좋아서 그러신것 같네요. 익숙한 if 문 말고 when 문이 보이면 좀 더 눈이 가는 뭔가가 있는거 같아요!

2024-07-09 21:01 UTC, Unagi-zoso commented on src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/application/FoodSpotsSearchService.kt
> +                    OperationStatus.TEMPORARILY_CLOSED
혹시 이 부분은 어떤 역할인지 알 수 있을까요? 
제 생각엔 openValue 에 대입을 해야할 것 같은데 이대로면 map 이 첫 원소 접근 시 
open 이 false 라면 임시휴업인데도 불구하고 openValue 가 OPEN 인 경우가 생길 수 있지 않을까 생각이 드네요.

제가 잘못 이해한거일 수 있는데 이런 흐름의 코드를 의도하신건 아닌가 싶네요. 아니라면 죄송합니다!!

```
val foodSpotsSearchResponses =
            result.map { foodSpots ->
                val openValue: OperationStatus =
                    if (foodSpots.open) {
                        foodSpots.foodSpotsOperationHours.find { operationHours ->
                            operationHours.dayOfWeek == dayOfWeek
                        }?.let {
                            val openTime = LocalTime.parse(it.openingHours, format)
                            val closeTime = LocalTime.parse(it.closingHours, format)
                            if (now.isAfter(openTime) && now.isBefore(closeTime)) {
                                OperationStatus.OPEN
                            } else {
                                OperationStatus.CLOSED
                            }
                        } ?: OperationStatus.CLOSED
                    } else {
                        OperationStatus.TEMPORARILY_CLOSED
                    }
```

2024-07-09 21:01 UTC, Unagi-zoso commented on src/test/kotlin/kr/weit/roadyfoody/search/foodSpots/presentation/api/FoodSpotsSearchControllerTest.kt
> +
혹시 then 부분을 누락하시진 않으셨나요? 다른 ControllerTest 에는 사용하신거 같은데..!
다른 이유가 있으시다면 조금 궁금합니다!

2024-07-10 02:20 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/application/FoodSpotsSearchService.kt
> +                    OperationStatus.TEMPORARILY_CLOSED
아 맞습니다! openValue에 대입을 안해줬네요 변경하겠습니다!

2024-07-10 02:21 UTC, jifrozen0110 commented on src/test/kotlin/kr/weit/roadyfoody/search/foodSpots/presentation/api/FoodSpotsSearchControllerTest.kt
> +
여러 부분을 수정하다보니 빠졌나봐요! 수정하겠습니다!

2024-07-10 04:28 UTC, konempty requested changes
너무 고생이 많으신데 피드백할게 몇개 보여서 코멘트 남깁니닷..
진짜 쪼금만더 고생 부탁드려요..!

2024-07-10 04:28 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/common/domain/query/CustomFunctionContributor.kt
> +            StandardSQLFunction("contains", StandardBasicTypes.BOOLEAN),
오호 이제는 해결이되었나요??

2024-07-10 04:28 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
> +    // 카테고리 //가게이름
오잉 ㅋㅋㅋ 여기 주석은 어떤의도일까요??

2024-07-10 04:28 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
> +        // todo : name 검색 현재 불가합니다.(CONTAIN 함수 인식을 못함) 수정 필요
아직도 안되나요..??

2024-07-10 04:28 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
> +                        },
여기도 takeIf를 이용하는 코드로 바꿔볼만 할것 같아요!

2024-07-10 04:28 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
> +                        ).from(
생각해보니까 굳이 selectDistinctNew가 아니라 selectDistinct만 써도 충분하지 않나요??
New 키워드가 붙으면 불필요하게 객체를 생성하는 과정이 들어갈거예요
그리고 Long이라는건 컴파일러가 알아서 유추가 가능해서 <Long>은 때도 괜찮을것 같아요!

2024-07-10 04:28 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
> +                            path(FoodSpotsFoodCategory::foodSpots)(FoodSpots::id),
어 그러고 보니 groupBy기준이 FoodSpots::id니까
selectDistict가 아닌 그냥 select를 써도 될것 같아요!

2024-07-10 04:28 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
> +    }
요기의 중복된 코드를 묶어보는건 관심없으신가요?? ㅋㅋㅋㅋ

2024-07-10 04:28 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/application/FoodSpotsSearchService.kt
> +                    it.operationHoursList.map {
여기선 map의 결과가 사용되지 않고 단순히 리스트를 순회하시기위해 사용하는것 같은데
그럴땐 it.operationHoursList.forEach로 순회하는게 좋습니다~!

2024-07-10 04:28 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/application/FoodSpotsSearchService.kt
> +                var openValue: OperationStatus = OperationStatus.OPEN
기본값은 닫혀있다로 보는게 맞을것 같아요!

2024-07-10 04:28 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/application/FoodSpotsSearchService.kt
> +                }
여기 코드를 좀더 정리하면 아래와 같이 하는게 좋을것 같아요!
```kotlin
                val openValue: OperationStatus =
                    if (it.open) {
                        it.operationHoursList
                            .firstOrNull {
                                it.dayOfWeek == dayOfWeek
                            }?.let {
                                if (now.isAfter(
                                        LocalTime.parse(it.openingHours, format),
                                    ) &&
                                    now.isBefore(LocalTime.parse(it.closingHours, format))
                                ) {
                                    OperationStatus.OPEN
                                } else {
                                    OperationStatus.CLOSED
                                }
                            } ?: OperationStatus.CLOSED
                    } else {
                        OperationStatus.TEMPORARILY_CLOSED
                    }
```

2024-07-10 04:28 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/application/FoodSpotsSearchService.kt
> +            result.map { it ->
여기서 사용할 변수명을 따로 지정하지 않아도 기본적으로 it으로 할당되니까
it -> 는 빼도될것 같아요!

2024-07-10 04:28 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/application/FoodSpotsSearchService.kt
> +                    foodCategories = it.foodCategoriesList.map { it.foodCategory.name },
지금 요코드를 보면
**it**.foodCategoriesList의 it과
map { **it**.foodCategory.name }의 it이 서로다른 대상을 가리키고있는데 이름이 같죠?
이러면 다른사람들에게 혼란을 줄수 있어서 중첩된 람다를 사용하게 되면 내부 람다에서는 이름을 지정해주는게 좋습니다!
나중에 시간되시면 이펙티브 코틀린도 공부해보시면 좋을것 같아요 ㅋㅋㅋ

2024-07-10 04:28 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/dto/FoodSpotsSearchCondition.kt
> +    @Size(min = 1, max = 60, message = "검색어는 1자 이상 60자 이하로 입력해주세요.")
여기에 field: 붙혀야 하지 않나요..??

2024-07-10 04:30 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/common/domain/query/CustomFunctionContributor.kt
> +            StandardSQLFunction("contains", StandardBasicTypes.BOOLEAN),
아니요...이것도 동작을 안합니다...우선 공유차원에서 올려두었습니다

2024-07-10 04:30 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
> +    // 카테고리 //가게이름
아 제가 개발하면서 안놓칠려고 써놨는뎈ㅋㅋㅋ지우겠습니다!

2024-07-10 04:30 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
> +        // todo : name 검색 현재 불가합니다.(CONTAIN 함수 인식을 못함) 수정 필요
네....

2024-07-10 04:32 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
> +                        },
동작을 안해서 이런저런방법으로 수정 하다가 저렇게 적용된것같네요! 동작하면 수정하겠습니다.
우선 심플하게 동작하는지 확인하고싶어 최대한 제가 쉽게보는 코드로 작성해놨습니다

2024-07-10 04:59 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
> +    }
앗 이유를 여쭤봐서 수정을 권하는지 파악못했습니다! 수정하겠습니다!

2024-07-10 05:00 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
> +                            path(FoodSpotsFoodCategory::foodSpots)(FoodSpots::id),
아 그렇네요! 시정하겠습니다.

2024-07-10 05:10 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/application/FoodSpotsSearchService.kt
> +                }
반영하겠습니다!

2024-07-10 05:10 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/application/FoodSpotsSearchService.kt
> +                    foodCategories = it.foodCategoriesList.map { it.foodCategory.name },
넵! 반영하겠습니다!

2024-07-10 05:51 UTC, konempty commented
<img width="403" alt="스크린샷 2024-07-10 오후 2 50 1" src="https://github.com/Weit-2nd/roady-foody-server/assets/44064530/fc8d559a-4f84-4d65-a2df-e81719bf94e4">
@jifrozen0110 리뷰 반영이 되면 리뷰 재요청을 주셔야 제가 리뷰를 해도 되는지, 아니면 아직 반영중인지 알수있어요..!

2024-07-10 05:53 UTC, jifrozen0110 commented
아 그렇군요! 항상 반영하면 빠르게 리뷰주셔서 몰랐습니다. 다음부턴 re-request 날리겠습니다!

2024-07-10 07:08 UTC, konempty commented on src/test/kotlin/kr/weit/roadyfoody/search/foodSpots/application/FoodSpotsSearchServiceTest.kt
> +            val query: FoodSpotsSearchCondition =
<img width="766" alt="스크린샷 2024-07-10 오후 2 57 39" src="https://github.com/Weit-2nd/roady-foody-server/assets/44064530/736b2d47-d868-4835-92ed-db5c3192f570">

요기도 지워달라고 그러네요 ㅋㅋㅋ

2024-07-10 07:08 UTC, konempty commented on src/test/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepositoryTest.kt
> +class FoodSpotsRepositoryTes(
이름에서 마지막에 t가 빠졌네요 ㅋㅋㅋ
tes -> test

2024-07-10 07:08 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/common/domain/query/CustomFunctionContributor.kt
> +            StandardSQLFunction("contains", StandardBasicTypes.BOOLEAN),
ㅋㅋㅋㅋ 조금 확인을 해봤는데 몇가지 잘못된게 있네요
1. contains의 반환형은 boolean이 아닌 integer인것 같다
<img width="679" alt="스크린샷 2024-07-10 오후 3 58 31" src="https://github.com/Weit-2nd/roady-foody-server/assets/44064530/66579866-e712-4362-9846-06f43005d980">

2. 그리고 contains의 결과가 0보다 큰지 확인해야한다
<img width="644" alt="스크린샷 2024-07-10 오후 3 59 05" src="https://github.com/Weit-2nd/roady-foody-server/assets/44064530/65282066-d132-4bc6-b45e-767caf95b6e4">

3. context 인덱스의 경우 인덱스가 실시간으로 측정되지않는다 (sync on commit 상황에만 측정)
<img width="918" alt="스크린샷 2024-07-10 오후 4 00 46" src="https://github.com/Weit-2nd/roady-foody-server/assets/44064530/0f4a8e94-185a-4941-95b6-b4b30f910135">

4. 따라서 beforeEach에서 DB에 저장하게된다면 트랜잭션 내부 범위라 commit이 되지 않아 인덱스가 측정되지 않기에
     BeforeTest처럼 트랜잭션 외부범위에서 저장을 해야 DB에 커밋을 치고 인덱스가 측정된다
<img width="1852" alt="스크린샷 2024-07-10 오후 4 02 31" src="https://github.com/Weit-2nd/roady-foody-server/assets/44064530/6cd4fce4-2f4f-4ea6-b91b-5f1008ff7c39">

5. 이렇게 하면 테스트가 돌아간다
<img width="392" alt="스크린샷 2024-07-10 오후 4 08 06" src="https://github.com/Weit-2nd/roady-foody-server/assets/44064530/11486ea3-1900-40c4-88b7-01a0fb671e00">

2024-07-10 09:14 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/common/domain/query/CustomFunctionContributor.kt
> +            StandardSQLFunction("contains", StandardBasicTypes.BOOLEAN),
와 대박 정말 숭배하겠습니다ㅜ 정말 이 부분때문에 고민 많이하였는데 
궁금한게 index 측정이 안되면 쿼리가 작동을 안하는걸까요?
contains는 좀 억울한게! [공식문서](https://docs.oracle.com/en/database/other-databases/nosql-database/23.3/sqlreferencefornosql/contains_function.html) 찾아서 boolean이 return값인걸 확인하여 작성한건데
저거랑 다른 함수인가보네요😢

2024-07-10 09:19 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/common/domain/query/CustomFunctionContributor.kt
> +            StandardSQLFunction("contains", StandardBasicTypes.BOOLEAN),
ㅋㅋㅋㅋ 공식문서까지 찾아보고 나온 결과였군요
>궁금한게 index 측정이 안되면 쿼리가 작동을 안하는걸까요?

다른 인덱스 들은 DB 커밋이 되는것과 상관없이 인덱스에 데이터가 추가되는데 반해
context index타입들은 커밋되기전까진 index에 아무 데이터도 들어가지 않아서 검색결과가 없는것 같아요!

2024-07-10 09:21 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/common/domain/query/CustomFunctionContributor.kt
> +            StandardSQLFunction("contains", StandardBasicTypes.BOOLEAN),
와ㅏㅏㅏ 진짜 대단하세요!! 이해했습니다🙇🏻‍♀️🙇🏻‍♀️
너무 신나서 바로 re request 보냈는데 위 takeIf 등 반영해두겠습니다!

2024-07-10 09:22 UTC, konempty approved these changes
고생하셨습니다 👍 👍 
별 이상한 억까를 다 당하셔서 고생이 진짜 많으셨네요 ㅋㅋㅋㅋ
코멘트 하나 남겼는데 요것만 반영되면 머지해도 좋을것 같습니다~!

2024-07-10 09:22 UTC, konempty commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
> +                        },
요거 이제 TODO 내용대로 정리하면 좋을것 같습니다~!

2024-07-10 09:37 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/foodSpots/repository/FoodSpotsRepository.kt
> +                        },
와 코멘트가 100이 넘었네요!!
끝까지 코드리뷰 해주셔서 감사합니다 ☺️

2024-07-10 09:38 UTC, lin-chae approved these changes
엄청난 양의 코드네요! 지언님 코드를 보고 모르는 점 찾아보면서 새로 아는 점이 많네요ㅎㅎ

2024-07-10 09:38 UTC, lin-chae commented on src/main/kotlin/kr/weit/roadyfoody/common/domain/query/QueryDomainDsl.kt
> +
이렇게 따로 빼내는 방법을 처음 알았는데, 깔끔하고 좋아보이네요

2024-07-10 09:38 UTC, lin-chae commented on src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/application/FoodSpotsSearchService.kt
> +        val dayOfWeekValue = today.get(ChronoField.DAY_OF_WEEK)
ChronoField.DAY_OF_WEEK 월요일이 1이고 일요일이 7로 되어있는데 Enum에는 월요일이 0이고 일요일이 6으로 되어있는데 따로 문제가 없나요?

2024-07-10 09:39 UTC, jifrozen0110 commented on src/main/kotlin/kr/weit/roadyfoody/search/foodSpots/application/FoodSpotsSearchService.kt
> +        val dayOfWeekValue = today.get(ChronoField.DAY_OF_WEEK)
헉 완전 문제있습니다. 알려주셔서 감사합니다!

2024-07-10 11:34 UTC, merged